### ISSUE TITLE
Who gets to file CNCF Service Desk tickets?

### ISSUE THREAD

**Issue by philips** [kubernetes/steering#102]
I think we need to have a central list of people in the community repo with Steering as approvers for who can file a CNCF Service Desk ticket to request resources on the projects behalf. 

Currenly people are being added in an ad-hoc fashion without an authoritative published list IMHO. This isn't a problem, yet, but I don't think it is fair to the CNCF staff to arbitrarily infer who should and shouldn't have access.

Current list:

- Brian Grant
- Brendan Burns
- Brandon Philips
- Sarah Novotny
- Joe Beda
- Clayton Coleman
- Aaron Crickenberger
- Derek Carr
- Michelle Noorali
- Philip Wittrock
- Timothy St. Clair
- Davanum Srinivas
- Caleb Miles
- Jorge O. Castro
- Christoph Blecker  
- Ihor Dvoretskyi
- Jaice Singer DuMars
- Paris Pittman

cc @castrojo

**Comment by castrojo** [comment]
We could do a new file entirely, or we could do a combo of existing OWNERs files, perhaps k/k+k/community+steering?  

/assign

**Comment by dims** [comment]
let's do a new file with the list above and tell the CNCF folks that we will keep it up-to-date for them to consult.

**Comment by philips** [comment]
a new file is fine. I am apathetic on which repo it lands in.

**Comment by castrojo** [comment]
https://github.com/kubernetes/community/pull/3648

**Comment by spiffxp** [comment]
/close
I believe this has been addressed by the above
