### ISSUE TITLE
document unconscious bias training requirement

### ISSUE THREAD

**Issue by michelleN** [kubernetes/steering#104]
At the last steering meeting, we discussed that steering members would take an unconscious bias training course. I'd like for us to make this a requirement for steering members by documenting it in the steering repo. Perhaps we should create an on-boarding document that contains this kind of info?

**Comment by derekwaynecarr** [comment]
+1 - i would be happy to help take this issue.

**Comment by michelleN** [comment]
Thanks!

**Comment by timothysc** [comment]
Merged, closing.
