### ISSUE TITLE
Document process for proposals to Steering

### ISSUE THREAD

**Issue by michelleN** [kubernetes/steering#105]
It's unclear right now what the best way to proposal something to Steering is. Let's document this process / create a template for folks to follow. Perhaps something like this:
```
Problem Statement:
<insert 1-2 paragraphs>

Proposed Solution:
<insert 1-2 paragraphs>

Cost:
<bullet points>

Open Questions:
<bullet points>

Next Steps:
<bullet points>

Other Considerations and Notes:
<bullet points>
```

**Comment by timothysc** [comment]
FWIW I think the k8s/org group did an excellent job WRT issue templates. 
https://github.com/kubernetes/org/issues/new/choose

**Comment by derekwaynecarr** [comment]
i like the issue template as a means of asking a question to steering.  i
like a more formal write-up template as a means of presenting a solution.

**Comment by nikhita** [comment]
/remove-lifecycle rotten

xref https://github.com/kubernetes/steering/issues/131 - for issue templates
