### ISSUE TITLE
Does steering require admin privileges to kubernetes/kubernetes and kubernetes/community repos

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/steering#107]
https://github.com/orgs/kubernetes/teams/steering-committee/repositories

The current teams that have Admin access to kubernetes/kubernetes are:
- https://github.com/orgs/kubernetes/teams/release-managers - needed to create branches and for manual pushes for release branches
- https://github.com/orgs/kubernetes/teams/kubernetes-feature-branch-admins - same reasons, but for feature branches
- https://github.com/orgs/kubernetes/teams/owners - implicitly have admin access over all repos
- https://github.com/orgs/kubernetes/teams/steering-committee - ostensibly we are stewards of the project, and this is one of its most important repos

The current teams that have Admin access to kubernetes/community are:
- https://github.com/orgs/kubernetes/teams/community-admins - this is a mix of people that probably evolved organically, including some sig-contribex chairs/TLs, some github admin people, some steering
- https://github.com/orgs/kubernetes/teams/owners - implicitly have admin access over all repos
- https://github.com/orgs/kubernetes/teams/steering-committee - ostensibly we are stewards of the project, and this is one of its most important repos

I propose that steering remove our Admin access to both of these repos:
- Trust the existing repo admins to be stewards of their repos
- Trust the GitHub Admin Team to be a globally distributed responsive team that can respond to emergencies

**Comment by dims** [comment]
+1 from me

**Comment by spiffxp** [comment]
Done
![Screen Shot 2019-06-10 at 11 04 59 AM](https://user-images.githubusercontent.com/49258/59216041-a0fbd480-8b6f-11e9-96f8-5b80e0a1a8d5.png)

**Comment by spiffxp** [comment]
/close
I asked for lazy consensus here: [steering@ thread](https://groups.google.com/a/kubernetes.io/d/msg/steering/lKroTqDxCq8/gTMiSCHTAwAJ)

No objections and deadline passed, so this has now taken effect
