### ISSUE TITLE
We need a calendar for prompting us for different processes

### ISSUE THREAD

**Issue by dims** [kubernetes/steering#108]
We need a date based reminder for scheduling nominations, elections etc.

**Comment by nikhita** [comment]
If this calendar is only meant for elections, we can use the contribex shared calendar for this since elections are handled by contribex anyway.

**Comment by nikhita** [comment]
/remove-lifecycle stale

We have a steering-shared calendar now. Keeping this open to ensure we end up adding calendar events for different processes.

**Comment by nikhita** [comment]
Going to take a look at it this week and will follow up with contribex.
