### ISSUE TITLE
Process for Travel support for Kubernetes Contributors

### ISSUE THREAD

**Issue by dims** [kubernetes/steering#109]
See thread:
https://groups.google.com/a/kubernetes.io/d/msg/steering/12g6Ra1fDEs/9v07uRVDBQAJ

**Comment by dims** [comment]
So let's request sig-contribex to come up with a plan:
https://github.com/kubernetes/community/issues/3783

Already requested them on slack:
https://kubernetes.slack.com/archives/C1TU9EB9S/p1559853299034200

**Comment by dims** [comment]
@parispittman has a write up in https://github.com/kubernetes/community/issues/3783

**Comment by raelga** [comment]
Thanks for this initiative. :) :blue_heart:

**Comment by castrojo** [comment]
Draft: https://github.com/kubernetes/steering/pull/114

**Comment by michelleN** [comment]
next steps: @kubernetes/steering-committee - please review

**Comment by michelleN** [comment]
aim to merge this by August 21st.

**Comment by michelleN** [comment]
@kubernetes/steering-committee -- let's talk about costs and where funding comes from. Could come from KCS fund. Depends on how things work out for KCS funding.

**Comment by sftim** [comment]
Travel will be important again one day!
/remove-lifecycle rotten

**Comment by parispittman** [comment]
@idvoretskyi - the last thing I remember here is there was a new box to check on the diversity form that included contributors - what is the current status of this? Is it still a thing? Should we have a separate form for contributors? 

Let's try and have something in place for May in Valencia. Will put this on the agenda for SC Meeting Monday to get a SC owner to help drive with CNCF.

**Comment by idvoretskyi** [comment]
@parispittman honestly I don’t recall what was the last status on this - it was years ago :)

Let’s catch up on Monday, happy to kick this for Valencia in advance!

**Comment by justaugustus** [comment]
/assign
(from 12/6 Steering public meeting)

**Comment by justaugustus** [comment]
cc: @eddiezane

**Comment by justaugustus** [comment]
/assign @parispittman
(tag-team w/ me on survey)

**Comment by dims** [comment]
Looks like we didn't do this for KubeconEU and ended up with adhoc servicedesk ticket with a bunch of folks. Let's do this for Detroit please?

**Comment by parispittman** [comment]
[CNCFSD-1309](https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-1309) was filed that includes this ask + leads ask for promo codes to give away for recognition to contributors, etc.

**Comment by mrbobbytables** [comment]
I think we can close this now with the maintainers now being listed as an option under scholarships:
https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/attend/scholarships/

what does everyone else think?

**Comment by dims** [comment]
+1 to close it. we did good :)

![FrayedImprobableElephant-max-1mb](https://user-images.githubusercontent.com/23304/212762183-ffd0a905-eb4c-4368-bc95-0311eea81e6f.gif)

**Comment by palnabarun** [comment]
+1 from me too!

/pony yay

**Comment by cpanato** [comment]
+1 nice!
