### ISSUE TITLE
Contributor Summit Budget Transparency

### ISSUE THREAD

**Issue by parispittman** [kubernetes/steering#110]
following up from the steering committee meeting today re: general funding process,

it would be good to have transparency around the costs of the contributor summits. we have asked for things in the past to hear that they are too high for the budget. as we plan future summits and as they get larger, we'd like to know what we our options are. 

past summit information would be useful here, too.

**Comment by parispittman** [comment]
update: cncf now provides the event lead (a contribex /events owners file contributor) the budget. i appreciate the detail, too. thank you! 

steering question: should the lead provide steering with budget info as a friendly fyi? before, after, during? at all/trust?

**Comment by cblecker** [comment]
I'm happy to delegate oversight of the budget to ContribEx and the event lead. If there are concerns (either raised by CNCF, the event lead, or by Steering) then I believe the lead and CNCF should provide that budget transparency to steering on request.

**Comment by parispittman** [comment]
per steering committee, we are ok with the events lead taking this and steering being in the loop and taking escalations if necessary. we should probably write this down somewhere.

/close
