### ISSUE TITLE
Graduate Kubernetes in CNCF

### ISSUE THREAD

**Issue by caniszczyk** [kubernetes/steering#12]
Hey @kubernetes/steering-committee, we are starting the process to graduate some projects (e.g., https://github.com/cncf/toc/pull/69) in CNCF and would love to have Kubernetes be part of that process.

I've sketched out a rough doc that shows that kubernetes fulfills the requirements here: https://docs.google.com/document/d/18QORSz2_QzlFVDL86XzGXy0BwbO7LYsdSBraQ6iAGu0/edit#heading=h.hfdvv8nysu5h

I'd love consensus from the @kubernetes/steering-committee to move forward with this.

**Comment by caniszczyk** [comment]
friendly ping here @kubernetes/steering-committee

**Comment by bgrant0607** [comment]
Done!
