### ISSUE TITLE
Bosun should resolve all comments on the agenda at the end of public meetings.

### ISSUE THREAD

**Issue by jberkus** [kubernetes/steering#123]
The way it is now: 

Often the note-taker for a public SC meeting is not a member of the SC, and as such all of their notes are suggestions (I've been the note-taker several times).  Because nobody is assigned to integrated these "suggestions", they often don't get saved to the agenda until a week or more after the SC meeting.  This harms the ability of the community at large to see what was decided and discussed in the meeting.

Suggested resolution:

Someone who has edit rights on the document should resolve all suggestions/notes at the close of the meeting.  As the Bosun is always a member of the SC, this seems like a logical duty for them.

**Comment by parispittman** [comment]
per steering meeting, bosuns will now clear comments. we are also creating a how to bosun doc which this will be on including other info.

/close
