### ISSUE TITLE
Term limits on steering. 

### ISSUE THREAD

**Issue by timothysc** [kubernetes/steering#127]
Discussed on 20190904, there was a general question if we should outline both consecutive and lifetime term limits.

**Comment by philips** [comment]
I think we should have a lifetime limit and it should be roughly on the order of 10 years. Why?

Well, I think Kubernetes is a technology that is going to be with us for 30+ years in a big way. This means that there are people who will be full time dedicated to this project as their career for that period of time. During that time the contributor base will likely expand but there will be people who have very specific expertise that will be leading parts of the system for multiple decades potentially. I base these assumptions on my experience in the Linux Kernel ecosystem.

So, I think that 10 years of service balances time for these multi-decade career Kubernetes Contributors to lead on this committee while providing opportunities to recover from potential burn out of the work involved and also leaving space for others to step in during the 30+ years of project success.

**Comment by parispittman** [comment]
someone (maybe aaron) in steering to take lead on PR'ing in the policy so we can see what this would look like. no major dissent on the call today to what philips laid out above. more soon.

**Comment by nikhita** [comment]
@spiffxp friendly ping on this :wave: 

If you don't have the bandwidth to take this on, I'm happy to work on it too. :)

**Comment by spiffxp** [comment]
/assign @nikhita 
go for it

**Comment by nikhita** [comment]
I totally missed this. :woman_facepalming: 

Will add it back on my radar.
/unassign @spiffxp

**Comment by nikhita** [comment]
/unassign
/assign @parispittman 
(thanks for getting #175 going!)
