### ISSUE TITLE
README: update with new steering members

### ISSUE THREAD

**Issue by philips** [kubernetes/steering#128]
See https://groups.google.com/forum/#!topic/kubernetes-dev/1kZvBDGhSCU

**Comment by cblecker** [comment]
https://github.com/kubernetes/org/pull/1263

**Comment by cblecker** [comment]
https://github.com/kubernetes/community/pull/4145

**Comment by cblecker** [comment]
https://github.com/kubernetes/kubernetes-template-project/pull/30

**Comment by cblecker** [comment]
https://github.com/kubernetes/funding/pull/4

**Comment by cblecker** [comment]
https://github.com/kubernetes/steering/pull/130

**Comment by cblecker** [comment]
I think I got everything.
