### ISSUE TITLE
README: find new sc1 and sc2 @kubernetes.io owners

### ISSUE THREAD

**Issue by philips** [kubernetes/steering#129]
The SC1 and SC2 accounts are meant for one off maintenance of the kubernetes.io GSuite system. @jbeda and @philips currently own 1 and 2 respectively. We need to hand them off to new steering members.

**Comment by dims** [comment]
@philips - i can take one!

**Comment by parispittman** [comment]
I can take another

**Comment by philips** [comment]
@dims is now sc1.

@dims please put up a PR to update the README.

**Comment by dims** [comment]
Done! https://github.com/kubernetes/steering/pull/133
