### ISSUE TITLE
Unconscious Bias Training  

### ISSUE THREAD

**Issue by timothysc** [kubernetes/steering#132]
Per update, all members should complete on unconscious bias training course

xref - https://github.com/kubernetes/steering/issues/98 
xref - https://github.com/kubernetes/steering/blob/master/charter.md#inclusive-leadership-training

**Comment by cblecker** [comment]
I have completed this training.

**Comment by nikhita** [comment]
I have completed the training as well.

**Comment by parispittman** [comment]
I've completed the training.

**Comment by cblecker** [comment]
/assign @timothysc @derekwaynecarr @spiffxp @dims 

Can you all confirm that you've done this, and when you do, unassign yourself? Thank you!

**Comment by dims** [comment]
/unassign

yep. i've completed.

**Comment by timothysc** [comment]
/unassign 

I ... "believe" I completed the CNCF one, but VMware has an extensive series on this topic that I have to complete on an annual basis.

**Comment by spiffxp** [comment]
/unassign

finally figured out where to find my training certificate, yes I've completed this training

**Comment by cblecker** [comment]
This was documented in https://github.com/kubernetes/steering/pull/124

Just need to confirm that @derekwaynecarr has completed this, and we can close this out.

**Comment by nikhita** [comment]
/assign @lachie83 

@lachie83 if you have already done this training, feel free to unassign yourself :)

**Comment by cblecker** [comment]
link if either of you need it: https://training.linuxfoundation.org/training/inclusive-speaker-orientation/

**Comment by lachie83** [comment]
/unassign

I've completed this training.

**Comment by derekwaynecarr** [comment]
I have completed this training.
