### ISSUE TITLE
SC presence @ KubeCon SD

### ISSUE THREAD

**Issue by parispittman** [kubernetes/steering#134]
We need to coordinate and plan for the following activities:

1 - Contributor Summit. We have a 15 minute Q&A placeholder. It's possible to do whatever we want with this time but that's what we have now.

2 - Steering Committee panel on the main show community track. https://sched.co/UadL Thurs Nov 21 @ 220pm. Need to collect all panelists names and add to sched. update: all current members will be present and possibly jbeda

3 - In person private meeting. At least one hour. Need to find a time and a place. Doodle poll posted to SC members. update - doodle results in; sent calendar for Thursday night.

**Comment by nikhita** [comment]
This is now done. Video of the panel: https://youtu.be/0Su1kKlr9q0

/close
