### ISSUE TITLE
OWNERS file(s) curation.

### ISSUE THREAD

**Issue by timothysc** [kubernetes/steering#135]
As a community the primary means for routing issues and PRs to the appropriate stakeholders is via the OWNERS files.  Test infra folks have done a good job in adding automation to help enable auto-labeling so those issues and PRs can be triaged, however these files are very poorly maintained atm and SIGs that have not been curating these should be notified.  

We have seen this as an issue for a while, but we should help to empower and remediate this issue.   

xref: https://github.com/kubernetes/community/issues/1808
xref: https://github.com/kubernetes/community/issues/4149

/assign @dims @timothysc

**Comment by dims** [comment]
example of banging the drums - https://groups.google.com/d/msg/kubernetes-sig-leads/ZbYr0P9wsvE/zuHujtpGBAAJ

**Comment by dims** [comment]
cc @mrbobbytables
