### ISSUE TITLE
2019 Steering Committee Election Retro

### ISSUE THREAD

**Issue by nikhita** [kubernetes/steering#140]
The election officers for the 2019 Steering Committee Election created a retro doc - https://docs.google.com/document/d/1La9ZJPdvgLRzVH_RvE3Tmmx7uw_de8x8Ca4HoCkH8R0/edit.

The crossed out points are already addressed (most of them in https://github.com/kubernetes/community/pull/4148). This is a tracking issue to make sure that all other points in the doc don't get lost.

The following points from the retro doc still need to be addressed. Details about each point can be found in the doc.

- Process docs (add [release-style timeline events](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.16#timeline))
- Feedback from/to nominee
- Non-voter encouragement letters
- Devstats & voter google sheet
- Exemption forms
- Figure out how to allow voters to ask questions of the nominees
- Template for `Election “final warning” email`, `Ballot resend emails`, `Blog post templates`
- Clarify consequences of missing deadlines
- The voter qualification bar was maybe too low
- Some people didn’t receive ballots after 10 hours
- The CIVS email messages look untrustworthy
- Weekly Status Template
- Results notification

/cc @mrbobbytables @castrojo @idvoretskyi @bgrant0607

**Comment by mrbobbytables** [comment]
/assign
So I don't lose track + I can work on some of the items (release style timeline etc).

**Comment by mrbobbytables** [comment]
/remove-lifecycle stale

I'll bump this back up on the todo list.

**Comment by castrojo** [comment]
/close

Had a long discussion with Josh about this, the important changes have been made already. We have open items that are improvements to the email/CIVS process, but after some discussion it's clear that a github integrated application that implements a condorcet voting model is the way forward and not improving the CIVS methods. We're doing decent with what we have now and hyper optimizing this method isn't an efficient use of time. 

We need to sync with the CNCF on perhaps speccing out a generic simple app that implements this and removing the email requirements entirely, this would remove a ton of complexity. This is also something that could easily be consumed by the rest of the cloud native landscape. I'll file issues for that in the appropriate places.

**Comment by castrojo** [comment]
Follow up issue: https://github.com/cncf/sig-contributor-strategy/issues/51
