### ISSUE TITLE
Craft Policy on Requesting help for key areas

### ISSUE THREAD

**Issue by timothysc** [kubernetes/steering#141]
@dims

**Comment by dims** [comment]
cc @daminisatya

**Comment by dims** [comment]
prior art:
- https://discuss.kubernetes.io/c/contributors/role-board
- https://github.com/kubernetes/sig-release/blob/master/release-team/README.md

**Comment by daminisatya** [comment]
+1

**Comment by daminisatya** [comment]
cc @miteshskj

**Comment by miteshskj** [comment]
Policy draft - https://docs.google.com/document/d/1djCfmg4dBs62AhoSjiJsL4NgEPsVTGccd9xRQzX6J8o/edit#heading=h.67xvy3ozb0w

cc @dims @daminisatya

**Comment by parispittman** [comment]
https://lists.cncf.io/g/cncf-toc/message/4142 - similar type of process going on at cncf toc level

**Comment by dims** [comment]
/close

we are working on a bunch of things including a reporting process for sigs and wg. will pick this up later once we figure out if there are still gaps
