### ISSUE TITLE
CNCF representative in SC public meetings

### ISSUE THREAD

**Issue by nikhita** [kubernetes/steering#145]
Since a considerable number of topics in Steering Committee meetings usually end up with "let's ask CNCF about this", it would be nice to have an official CNCF representative (at least one) in the SC public meetings. 

The CNCF rep can decide whether to attend the meeting depending on the agenda.

@dankohn @caniszczyk @idvoretskyi can y'all make this happen and decide who this representative would be? Of course, it isn't necessary that the same person needs to show up in all meetings. If they can't make it, it would be great if another CNCF rep showed up. :)

**Comment by idvoretskyi** [comment]
@nikhita Happy to be a CNCF representative.

**Comment by idvoretskyi** [comment]
@nikhita I assume we may close this issue unless there are further questions on this.

**Comment by cblecker** [comment]
@idvoretskyi Yes, if things are set on your side that either yourself (or someone else if you can't make it) can attend, I think we're good on this.

**Comment by idvoretskyi** [comment]
@cblecker yes, we are all set. Do you think this needs to be documented in the Steering documentation (eg. - https://github.com/kubernetes/steering/blob/master/README.md)?

**Comment by parispittman** [comment]
@idvoretskyi yes pls that would be awesome

**Comment by idvoretskyi** [comment]
/assign

I'll take care of it.

**Comment by idvoretskyi** [comment]
Done - https://github.com/kubernetes/steering/pull/148

**Comment by nikhita** [comment]
Fixed by https://github.com/kubernetes/steering/pull/148

/close
