### ISSUE TITLE
sig-governance meeting contradiction

### ISSUE THREAD

**Issue by parispittman** [kubernetes/steering#152]
[sig-gov roles](https://github.com/kubernetes/community/blob/master/committee-steering/governance/sig-governance.md)

first set of bullets:
Meet regularly, at least for 30 minutes every 3 weeks, except November and December

organizational management section:
SIG meets bi-weekly on zoom with agenda in meeting notes
SHOULD be facilitated by chairs unless delegated to specific Members

### Proposed Solution
should be consistent - pick one after discussion/comments

**Comment by parispittman** [comment]
sort of scope creeping myself but a note:
also in first set of bullets
 >on a YouTube playlist

should be expanded to say Kubernetes Community* YouTube playlist (not just any one)

**Comment by parispittman** [comment]
per steering meeting - PR in a change to have both bullets say once every three weeks

**Comment by cblecker** [comment]
+1
