### ISSUE TITLE
Steering Committee AMA - KubeCon EU 2020

### ISSUE THREAD

**Issue by cblecker** [kubernetes/steering#154]
### Problem Statement
Based on feedback from our panel in San Diego, we want to reprise our Steering Committee panel in Amsterdam.

### Attending
- @cblecker 
- @parispittman 
- @nikhita 
- @dims 
- @spiffxp 

### Proposed Agenda
- Introductions
- How is governance handled in the Kubernetes project
- What does Steering do specifically?
- Open the floor for questions

### What needs to be done
- Couple of slides?

**Comment by cblecker** [comment]
KubeCon EU has been rescheduled for August. Will confirm new set of attendees prior to this.

/assign
/lifecycle frozen

**Comment by nikhita** [comment]
From [1 June 2020 public steering meeting](https://docs.google.com/document/d/1qazwMIHGeF3iUh5xMJIJ6PDr-S3bNkT8tNLRkSiOkOU/edit#heading=h.s7u7rwmne94n), @lachie83 to follow up with CNCF to sign steering up for a AMA session. We'll present slides on what steering does, etc and then seed questions for AMA in the session.

/assign @lachie83 
/unassign @cblecker

**Comment by derekwaynecarr** [comment]
Just an update that since KubeCon EU is now virtual, I will attend and would participate in AMA as well.

**Comment by lachie83** [comment]
Session is scheduled - https://sched.co/cq9c. Wednesday, August 19 • 08:10 - 08:45

**Comment by lachie83** [comment]
I'm working with Nanci to iron out the details

**Comment by lachie83** [comment]
Slides are due by August 4th
