### ISSUE TITLE
Steering Election Officers for 2020 Election

### ISSUE THREAD

**Issue by castrojo** [kubernetes/steering#161]
### Problem Statement

It's time to start thinking of choosing election officers for the steering committee election. 

### Proposed Solution

We have been selecting election officers to get a rotation, trying to ensure that we have a mix of new and experienced election officers. I'd like to start this a month earlier because our prior election officers are now in other roles. Paris is on steering, and Bob/Jorge are cochairs of contribex. This only leaves Ihor as our experienced election officer (with 3 elections), and Briant Grant with 1.  

The election is (usually) time consuming so getting in new election officers to supplement the available pool wouldn't be a bad thing.

Bob and I think that having a former steering member was very valuable, and it might be prudent to ask bgrant or another emeritus if they'd like to participate. 

### Other Considerations, Notes, or References

- [ ] xref # https://github.com/kubernetes/steering/blob/master/elections.md#election-schedule-and-operation

**Comment by parispittman** [comment]
we should PR in the names of the past election officers and when they did it somewhere in the policy docs so then we can point to those folks; i know they are listed in each year's guide but having them on the policy will be beneficial. i can take this or someone else if they dont see the PR in the meantime.

**Comment by nikhita** [comment]
xref https://github.com/kubernetes/steering/issues/140 (issue about last year's election retro)

**Comment by nikhita** [comment]
From [1 June 2020 public steering meeting](https://docs.google.com/document/d/1qazwMIHGeF3iUh5xMJIJ6PDr-S3bNkT8tNLRkSiOkOU/edit#heading=h.s7u7rwmne94n):

- @parispittman to update policy langauge to say that contribex brings candidates to steering by july 1
- @nikhita and @spiffxp to follow up with @mrbobbytables to discuss criteria for members of standing 
- @cblecker to take care of executing the policy for the next election

**Comment by jberkus** [comment]
I am available to help with this.

**Comment by nikhita** [comment]
Assigning people mentioned in https://github.com/kubernetes/steering/issues/161#issuecomment-637048450, so that we don't forget about this...

/assign @parispittman @nikhita @spiffxp @cblecker

**Comment by castrojo** [comment]
Contribex has reached lazy concensus and are recommending the following people for election officers: @jberkus @idvoretskyi @jdumars 

@castrojo and @mrbobbytables will be available as shadows for them. 

https://groups.google.com/u/1/g/kubernetes-sig-contribex/c/ySrRy3WLoMY

**Comment by dims** [comment]
+1 to  @jberkus @idvoretskyi @jdumars as officers and for @castrojo and @mrbobbytables as shadows!

**Comment by spiffxp** [comment]
+1

**Comment by lachie83** [comment]
+1

**Comment by cblecker** [comment]
+1

**Comment by parispittman** [comment]
+1

**Comment by nikhita** [comment]
+100 :tada:

**Comment by cblecker** [comment]
@castrojo This has been approved by the Steering Committee.

/assign @jberkus @idvoretskyi @jdumars 
Welcome, and thank you for agreeing to be election officers this year. Please kick off the process!

**Comment by nikhita** [comment]
I'll close this issue since we've decided the election officers now. Let's create new issues for any tasks related to the election going forward :)
