### ISSUE TITLE
Working Group Annual Reports: final planning 

### ISSUE THREAD

**Issue by parispittman** [kubernetes/steering#164]
### Problem Statement
We’ve landed the first stage of community group reporting and after conversations with Steering, we’ve decided we should roll this out to just working groups this year. We need a roll out process and guide. 

### Proposed Solution
Steering liaisons go to working group meetings and work with those organizers on completing the annual report

### Open Questions
- [x] what’s the time line?
	- [x] suggested 30 days to complete - ask if folks need more time
- [x] what do liaisons need to be successful with coaching or preparing organizers?
   - kdev email 
   - template for points to hit 
   - if there are follow up questions, steering sets an issue in this repo 
- [ ] smooth out the what’s after the reports - blog post summarizing with links

### Next Steps
- [x] complete the steering liaisons issue
- [x] complete the template for questions
- [x]  target July 1 or next public steering committee meeting for the announcement 
        - [x] k-dev by July 1
        - [ ] blog post by July 8 [authored by @divya-mohan0209 from marketing team]
        - [x] chairs and tech leads 

### Other Considerations, Notes, or References
- [ ] #153
- [ ] #159

**Comment by nikhita** [comment]
Going to reopen this since we still have a few WG annual reports that need to be PR'd in.
