### ISSUE TITLE
Request for calendar@kubernetes.io gsuite account. 

### ISSUE THREAD

**Issue by castrojo** [kubernetes/steering#166]
### Problem Statement
SIGs aren't inviting the community calendar to their meetings.  We just did an audit and 36(!) SIG and WG meetings are totally missing from the community calendar. Due to the way we were initially set up SIGs need to add `cgnt364vd8s86hr2phapfjc6uk@group.calendar.google.com` to their meetings and the instructions are buried on top of that (I'm filing separate issues for that.)

### Proposed Solution
Contributor experience is currently asking SIGs to add contributors@kubernetes.io as owners to their mailing lists so that we can automate meeting changes to the public calendar.

In order to do this we'd like a gsuite alias, `calendar@kubernetes.io`, which will be unprivileged (we can't reuse an existing account for this unfortunately). 

This will allow any SIG chair to have an easily rememberable name to invite the community to a meeting, and we'll use this alias to automate that for SIGs as they give us permissions to manage their lists.

/cc @mrbobbytables

**Comment by nikhita** [comment]
@castrojo can you also add details on who would be owners/members of `calendar@kubernetes.io`?

**Comment by mrbobbytables** [comment]
It'd have to be a named account similar to `contributors@kubernetes.io` =/ It has be an account with its own calendar.

The workflow would be that account to join all the community group mailing lists which should aggregate all their meeting invites to its personal calendar.  For reference an example one off gmail account that joined contribex, release and testing's mailing lists:
https://calendar.google.com/calendar/embed?src=k8s.calendar.test%40gmail.com&ctz=America%2FDetroit

Access wise at this point in time would be the contribex leads. Ideally very little would have to be done with that account once live. -- Just have it join other ML when a new community group is created.

**Comment by cblecker** [comment]
+1 to this. I know we want to minimize the amount of shared principal gsuite accounts, but the benefits of this are large and it would make things way easier for sig chairs

**Comment by dims** [comment]
+1 from me as well.

**Comment by nikhita** [comment]
+1 from me! Thank you so much for wrangling the mystical calendars! :sparkles:

**Comment by nikhita** [comment]
I have added this as an agenda item to the next SC meeting (July 6) to get feedback/approval from SC members

**Comment by nikhita** [comment]
Discussed in the steering meeting today. Steering is ok with moving ahead with `calendar@kubernetes.io` and `sig-foo-leads@kubernetes.io`. We'd also like to delegate gsuite group creation decisions to sig-contribex/wg-k8s-infra, I'll write down the policy on we'd split delegation between the two groups.

**Comment by parispittman** [comment]
account has been created. calendar@kubernetes.io
temp credentials assigned to contribex chairs

/close
