### ISSUE TITLE
code of conduct committee elections

### ISSUE THREAD

**Issue by parispittman** [kubernetes/steering#169]
July 21 - Nominations open (reminder sent to kdev on July 27th)
July 28 - Nominations close 
July 29 - Steering to vet nominees
August 4 - Steering to conduct elections
August 6 - New members notified
August 7 - Induct new members

**Comment by parispittman** [comment]
updates: all 7 members voted by 11:58AM PDT. Poll has now ended. 

Top 3 will be shared with CoCC before announcement. More soon.

**Comment by spiffxp** [comment]
/close
Results have been announced and PR'ed in https://github.com/kubernetes/community/pull/5018
