### ISSUE TITLE
Add SC liaisons for committees

### ISSUE THREAD

**Issue by nikhita** [kubernetes/steering#170]
In #159 and #168, we added Steering Committee liaisons for SIGs, WGs and UGs but we left out committees because they don't need to submit annual reports.

@parispittman suggested that we should also add SC liaisons for committees so that we have good feedback loops with them (thanks, Paris!)

fyi @divya-mohan0209 this might affect the blog post :)

**Comment by divya-mohan0209** [comment]
Yay, more content! Thank you for thinking of me @nikhita :)

**Comment by celestehorgan** [comment]
One comment: the purpose of the Committees is to do work that needs to be done in private. As such:

1. What are the expectations for a liaison? Will that liaison attend committee meetings, be in the committee channel, etc.? 
2. What is Steering's expectation for these liaisons reporting back?

**Comment by parispittman** [comment]
@celestehorgan there are no reporting duties and liaisons will be part of public channels only; this is mainly a way for us to flow information better specifically governance changes and events. An example for cocc’s liaison would be to remind about elections (both cocc and steering) and then possibly help start it like I’ve done in the past.

**Comment by justaugustus** [comment]
Opened https://github.com/kubernetes/community/pull/6260 to continue the discussion.
/assign

**Comment by justaugustus** [comment]
From @tpepper in [Steering agenda doc](https://docs.google.com/document/d/1qazwMIHGeF3iUh5xMJIJ6PDr-S3bNkT8tNLRkSiOkOU/edit?disco=AAAARHKrbeY):
> an idea not from the meeting live:  Can committees be asked to give a read-out in the Annual Reports?  CoCC effectively has one already in the new Conduct Transparency Report.  Similar from sec. response could be informative to track abstract workload and committee internal ops health.
