### ISSUE TITLE
sig-chairs should do wg annual reports in 2021

### ISSUE THREAD

**Issue by parispittman** [kubernetes/steering#172]
discuss changing the process for annual reports for 2021 to have sig chairs bubble up the working group annual reports vs the wg-organizers.

**Comment by parispittman** [comment]
some SC members are explicitly -1 on this; more discussion and will keep this open until wg reports are officially over

**Comment by justaugustus** [comment]
Since I raised this, I think I would probe on what the value/intention of SIG sponsorship of a WG is, without some expectation of SIG oversight.
