### ISSUE TITLE
Heads up to community over lead changes in SIGs/WGs

### ISSUE THREAD

**Issue by dims** [kubernetes/steering#179]
Currently we do not have a way to inform the community when new folks come in or folks step down in leadership positions. So there is no opportunity to either welcome them or thank them. Also there is no way folks will get to know unless they are directly affected by the changes either since folks don't watch github PR merges.

Let's make it easier to showcase the leadership changes as this will also give an opportunity to give people a chance to chime in if needed. How about we recommend a light weight process around informing folks with some kind of feedback/escalation mechanism that kicks in around the time a github PR merges with a leadership change.

thanks,
Dims

**Comment by nikhita** [comment]
/assign

created https://github.com/kubernetes/community/pull/5291
