### ISSUE TITLE
Onboard new SC members - October 2020

### ISSUE THREAD

**Issue by cblecker** [kubernetes/steering#180]
[Onboarding checklist](https://github.com/kubernetes/steering/blob/master/onboarding.md) for @mrbobbytables and @liggitt 

- [x] All new members must complete the [Inclusive Leadership Training]
within 30 days from the date of their appointment.

- [x] Update the following files in the respective repos:
  - [x] [kubernetes/steering]: `OWNERS_ALIASES` and `README.md`
  - [x] [kubernetes/community]: `sigs.yaml` and auto-generated content
  - [x] [kubernetes/org]: `OWNERS_ALIASES` and the `steering-committee`
    GitHub team
  - [x] [kubernetes/funding]: `OWNERS_ALIASES`
  - [x] [kubernetes/k8s.io] - update steering@kubernetes.io and steering-private@kubernetes.io in `groups/groups.yaml`

- [x] Add new members to the `steering-private` slack channel and
  remove emeritus members.

- [x] Add new members to the CNCF Service Desk and remove emeritus
  members.

- [x] Add new members to the [cncf-kubernetes-maintainers] mailing list.

- [x] If a GSuite [top-level account] is owned by an emeritus member,
  transfer it to an existing member.

- [x] If [Zoom license credentials] were owned by a majority of emeritus
  members, share them with exisiting members. The Zoom host key is
  accessible to all members and is a pinned message in the `steering-private`
  slack channel.

- [x] Set up a private meeting to go over backlog.

- [x] If an emeritus member is one of the @kubernetesio Twitter account contributors,
  transfer access to an existing member.

[Inclusive Leadership Training]: /charter.md#inclusive-leadership-training
[kubernetes/steering]: https://github.com/kubernetes/steering
[kubernetes/community]: https://github.com/kubernetes/community
[kubernetes/org]: https://github.com/kubernetes/org
[kubernetes/funding]: https://github.com/kubernetes/funding
[kubernetes/k8s.io]: https://github.com/kubernetes/k8s.io
[cncf-kubernetes-maintainers]: https://lists.cncf.io/g/cncf-kubernetes-maintainers
[top-level account]: /README.md#top-level-accounts
[Zoom license credentials]: /README.md#zoom-admins

**Comment by liggitt** [comment]
I did the [Inclusive Leadership Training](https://ti-user-certificates.s3.amazonaws.com/e0df7fbf-a057-42af-8a1f-590912be5460/a3971ba1-d762-4cca-9956-e91f688ab7f1-jordan-liggitt-the-inclusive-speaker-orientation-lfc101-certificate.pdf) in July, not sure if that counts

**Comment by mrbobbytables** [comment]
I did as well 👍 
[link](https://ti-user-certificates.s3.amazonaws.com/e0df7fbf-a057-42af-8a1f-590912be5460/f744a94e-40ef-404c-abe4-af1a4c71366d-bob-killen-the-inclusive-speaker-orientation-lfc101-certificate.pdf)

**Comment by cblecker** [comment]
Yeah, this is recent enough to be fine IMO

**Comment by mrbobbytables** [comment]
PRs have been made to update:
-  README (https://github.com/kubernetes/steering/pull/181)
- sigs.yaml (https://github.com/kubernetes/community/pull/5216)
- k/org (https://github.com/kubernetes/org/pull/2260)
- funding (https://github.com/kubernetes/funding/pull/13)

**Comment by nikhita** [comment]
> Add new members to the CNCF Service Desk and remove emeritus
members.

> Add new members to the cncf-kubernetes-maintainers mailing list.

@idvoretskyi can you help with this? :)

**Comment by idvoretskyi** [comment]
@nikhita happy to, please email or DM me with the preferred email addresses, I'll invite folks to the ServiceDesk.

**Comment by liggitt** [comment]
Ran across https://docs.google.com/spreadsheets/d/1Pr8cyp8RLrNGx9WBAgQvBzUUmqyOv69R7QAFKhacJEM/edit today, not sure if that's synced from the CNCF mailing list or not, but added to the checklist in https://github.com/kubernetes/steering/pull/182 just in case

**Comment by liggitt** [comment]
> * If [Zoom license credentials](/README.md#zoom-admins) were owned by a majority of emeritus
>   members, share them with exisiting members.

zoom credentials shared with @mrbobbytables

**Comment by liggitt** [comment]
> * Set up a private meeting to go over backlog.

Added to October 19th [agenda](https://docs.google.com/document/d/1qazwMIHGeF3iUh5xMJIJ6PDr-S3bNkT8tNLRkSiOkOU/edit#heading=h.tgysnkq3qm4w)

**Comment by cblecker** [comment]
I think the whole checklist is done.

@liggitt @mrbobbytables: we all good?

**Comment by liggitt** [comment]
yup, all done
