### ISSUE TITLE
Artifact Hub 

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/steering#188]
### Problem Statement
Kubernetes Helm repos are being listed on the [Artifact Hub](https://artifacthub.io/) (another CNCF project). There is a Kubernetes organization to list them under. Organizations can have multiple users as members.

Right now, there is no one on the steering committee or who has been appointed by the steering committee to be listed on the organization for Kubernetes on the Artifact Hub.

### Proposed Solution
Steering committee members or some people they appoint are setup to manage the org on the Artifact Hub. It's minimal work (if there ever is any). This way the Kubernetes project is in control of this channel.

### Cost
None

### Next Steps
- [ ] Decide how to proceed
- [ ] Let @mattfarina know who to setup with access

**Comment by dims** [comment]
@mattfarina would it be possible to add the sc1/sc2/sc3 accounts as members? ( see https://github.com/kubernetes/steering#top-level-accounts )

**Comment by mattfarina** [comment]
@dims If someone creates accounts on the artifact hub with those logins then they can be added. If I remember right, those email addresses are managed by google so you can use the google login button to login and setup the account. Once that's done I just need to invite the username.

**Comment by cblecker** [comment]
@mattfarina I created an artifact hub account for myself if you want to add me as an immediate term bus factor reduction. I'm also going to take on figuring out where this can safely go. Sorry for the delay -- this fell off of radar.

**Comment by stevehipwell** [comment]
What owner information needs adding to the _artifacthub-repo.yml_ file so a repository can be claimed by the Kubernetes SIGs organisation? I'll open PRs for [Metrics Server](https://artifacthub.io/packages/helm/metrics-server/metrics-server) & [External DNS](https://artifacthub.io/packages/helm/external-dns/external-dns) once I know this.

**Comment by stevehipwell** [comment]
@dims just following this up to see if there is a blocker here that I can help with?

**Comment by dims** [comment]
@stevehipwell i've managed to grab metrics-server and external-dns to SC1:
- https://artifacthub.io/packages/search?ts_query_web=external-dns&sort=relevance&page=1
- https://artifacthub.io/packages/search?ts_query_web=metrics-server&sort=relevance&page=1

Also see issue above to transfer the 2 orgs to SC1 as well. once thats one, we still have to activate SC2 and SC3 for which i will ping folks needed ( https://github.com/kubernetes/steering/#top-level-accounts )

@parispittman @mrbobbytables Can you please log into https://artifacthub.io/ using the SC2 and SC3 id's and create a user? ( i'll then request you get the org admin access to like i did in https://github.com/artifacthub/hub/issues/1684 )

**Comment by parispittman** [comment]
@dims SC2 is now signed up

**Comment by dims** [comment]
@parispittman thanks! please go back into the web ui and accept the invitation and we are all set!

**Comment by justaugustus** [comment]
/assign @mrbobbytables 
(from 12/6 Steering public meeting)

**Comment by mrbobbytables** [comment]
@dims sc3 has signed up

**Comment by dims** [comment]
@mrbobbytables invited sc3 to both `kubernetes` and `kubernetes-sigs` artifacthub orgs

**Comment by mrbobbytables** [comment]
@dims done.
I think this is good to close now?

**Comment by dims** [comment]
yes!

/close
