### ISSUE TITLE
Steering Emeritus List

### ISSUE THREAD

**Issue by cblecker** [kubernetes/steering#189]
There's been a couple of times where we have wanted to reach out to all the steering emeritus members. Should we consider creating an e-mail list to hit all these folks at once?

We can make it member-only to send to keep spam low.

**Comment by derekwaynecarr** [comment]
+1

**Comment by dims** [comment]
yes please!

**Comment by justaugustus** [comment]
Closed w/ https://github.com/kubernetes/k8s.io/pull/3051, https://github.com/kubernetes/k8s.io/pull/3199, and https://github.com/kubernetes/k8s.io/pull/3207. 
/assign
/close
