### ISSUE TITLE
broken link for steering meeting notes

### ISSUE THREAD

**Issue by heckj** [kubernetes/steering#19]
I was watching a recording of the steering meeting yesterday, and tried to find the notes that were referenced during the meeting. I [found a link in the README](https://github.com/kubernetes/steering/blame/master/README.md#L42), but the bit.ly link appears to be broken - and is returning a 404: https://bit.ly/k8s-steering

Wasn't entirely sure how to report it, or what the appropriate link fix would be, so opening an issue here...

**Comment by philips** [comment]
Fixed via #20 thanks!
