### ISSUE TITLE
CoCC shared drive

### ISSUE THREAD

**Issue by tpepper** [kubernetes/steering#192]
### Problem Statement
The CoCC has shared tracking documents which are non-public.  Like many earlier artifacts in the community, these are currently in a semi-arbitrary directory on Google Drive owned by a past member of the committee and current document ownership ACLs are a scattered representation of who was accessing each doc at its creation time. 

### Proposed Solution
We need to have consistent group access control on these across membership changes of the committee.  We can do so with a Shared Drive.  The drive and all documents in it would be owned by conduct@kubernetes.io.  Unlike other shared artifact stores, we desire not having sc* owners, but require sc* assistance in initial creation.

### Cost
Perhaps depending on the projects GSuite status there is cost associated with this request.  The volume of data is tiny.  These are almost entirely flat text documents, although there's a use case additionally for storing screen shots of point in time Slack/GitHub/other state.

### Open Questions
- [ ] How to ensure project has recovery path to ownership of conduct@kubernetes.io, but not risk general read ability on CoCC archive due to unintended config change?
- [ ] Should we change the peribolos config relative to CoCC membership to be in a subdirectory owned by conduct and in a blocked path to add a few more hurdles to accidentally exposing an archive tied to the group membership?

### Next Steps
- [ ] Next
- [ ] Steps

### Other Considerations, Notes, or References
- [ ] Fixes # 
- [ ] xref #

**Comment by tpepper** [comment]
Bump? @mrbobbytables you mentioned incoming issues would be triaged in regular process.  I know this came in with KubeCon, US Thanksgiving, end of year holidays, etc.  Would like to get this moving.

**Comment by mrbobbytables** [comment]
Sorry, this dropped off the radar for me.

/assign

**Comment by nikhita** [comment]
Funding request - https://github.com/kubernetes/funding/issues/16

**Comment by mrbobbytables** [comment]
The drive has been provisioned and access has been verified 👍 
/close
