### ISSUE TITLE
Update CNCF Service Desk Policy

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/steering#196]
### Problem Statement

The current policy for who can open CNCF service desk tickets on behalf of the project includes steering, k/community root owner, and SIG release leads. The k/community root owners no longer directly reflect those that should be able to open CNCF service desk tickets, and the independent list that steering maintains in [service-desk.md](https://github.com/kubernetes/steering/blob/master/service-desk.md) is quite out of date.

### Proposed Solution

Limit CNCF Service Desk access to the Steering Committee and SIGs leads that frequently interact with the CNCF (ContribEx and Release) and link to their respective owner files or readmes in k/community with an explanation as to why they have access.

Removing duplication of listing members who can access it should ensure the list stays up to date and the adding/removing of members access to the service desk can be made a part of the referenced SIGs onboarding.

### Open Questions

- Are there any other members or groups who should have access to the service desk that don't fall into the SC or a few named SIGs?

### Next Steps

- Discuss with SC for opinions and sign off
- Update policy documentation if approved

**Comment by parispittman** [comment]
+1

**Comment by liggitt** [comment]
+1

**Comment by nikhita** [comment]
+1 :)

**Comment by cblecker** [comment]
+1

**Comment by dims** [comment]
+1
