### ISSUE TITLE
Draft guidance for projects to go into maintenance and/or Attic

### ISSUE THREAD

**Issue by dims** [kubernetes/steering#198]
We had some guidance written down a while ago i think. will need to find it and dust it off

/assign @dims

**Comment by mrbobbytables** [comment]
Dropping a note from Slack:
As part of guidance for maintenance mode, a cursory audit should be done to check for in-project dependencies e.g. if a component happens to be used in an e2e test etc.

**Comment by dims** [comment]
https://hackmd.io/@XYdYH0X5SYC3DUYFF5Wylg/BkiiY3MGd/edit
