### ISSUE TITLE
Create 'execute summary' framework for annual reports

### ISSUE THREAD

**Issue by parispittman** [kubernetes/steering#202]
### Problem Statement
much of the answers provided from groups on the annual report can be summarized instead of reading 30+ docs, how can we create an executive summary style (maybe not that phrase) doc that can be a quick view in and also have links out so folks can have a better experience than searching through community folders. 

### Proposed Solution
- table of contents style
- any trends or high level conclusions that we can make
- call out anything important, issues, or accolades 
- Proposed framework: 
   - [ ] about us, 
   - [ ] what's a sig,
   - [ ]  what's a wg, 
   - [ ] themes, 
   - [ ] community milestones,
   - [ ] accolades, 
   - [ ] help wanted, 
   - [ ] risks(? needs to be renamed), 
   - [ ] table of contents 

### Open Questions
- [ ] What other areas do we want to address? 

### Next Steps
- [ ] create a draft framework and solicit reviews:  https://hackmd.io/R7hFEhc4SrOvaBl_vJDhEg

**Comment by mrbobbytables** [comment]
/assign
I can help out

**Comment by parispittman** [comment]
https://hackmd.io/R7hFEhc4SrOvaBl_vJDhEg
