### ISSUE TITLE
Third party dependencies in kubernetes

### ISSUE THREAD

**Issue by caniszczyk** [kubernetes/steering#21]
Hey @kubernetes/steering-committee, in CNCF we review all of our project dependencies to ensure they comply with the CNCF IP Policy: 

There have been a handful of dependencies that have been flagged as potential issues, usually a weak copyleft issue:

* heketi
* ratelimit
* yaml.v2
* hcl
* golang-lru
* dhcp4client
* influxdb (needs upgrade to switch out WTFPL subcomponent)

What would be the feasibility of switching these dependencies out or updating them to be compliant with the IP Policy? It would be great to put this on the SC agenda to discuss.

**Comment by quinton-hoole** [comment]
Thanks.  I've added it to the agenda.  http://bit.ly/k8s-steering-wd

**Comment by bgrant0607** [comment]
Re. ratelimit:

Noted here:
https://github.com/kubernetes/client-go/issues/357

was re-added by:
https://github.com/kubernetes/kubernetes/pull/38294

cc @liggitt

**Comment by liggitt** [comment]
Can be replaced with a golang ratelimiter (https://github.com/kubernetes/kubernetes/pull/38320) if we drop one of the metrics we are pulling from the current ratelimiter (which is of questionable value)

**Comment by thockin** [comment]
At some point I looked at all of the LGPL libs and they were all LGPL + static linking, which Go satisfies

**Comment by thockin** [comment]
heketi: I don't know this one

```
The REST API client code (in go and python) is released
under a dual license of Apache 2.0 or LGPLv3+.

The other parts of heketi (server, cli, tests, ...) are released
under a dual license of LGPLv3+ or GPLv2.
```

ratelimit: 
```
This software is licensed under the LGPLv3, included below.

As a special exception to the GNU Lesser General Public License version 3
("LGPL3"), the copyright holders of this Library give you permission to
convey to a third party a Combined Work that links statically or dynamically
to this Library without providing any Minimal Corresponding Source or
Minimal Application Code as set out in 4d or providing the installation
information set out in section 4e, provided that you comply with the other
provisions of LGPL3 and provided that you meet, for the Application the
terms and conditions of the license(s) which apply to the Application.
```

yaml.v2:
```
This software is licensed under the LGPLv3, included below.

As a special exception to the GNU Lesser General Public License version 3
("LGPL3"), the copyright holders of this Library give you permission to
convey to a third party a Combined Work that links statically or dynamically
to this Library without providing any Minimal Corresponding Source or
Minimal Application Code as set out in 4d or providing the installation
information set out in section 4e, provided that you comply with the other
provisions of LGPL3 and provided that you meet, for the Application the
terms and conditions of the license(s) which apply to the Application.
```

hcl: MPL - how do we feel about that?

golang-lru: MPL

dhcp4client: MPL

influxdb (needs upgrade to switch out WTFPL subcomponent): MIT.  We do not reference the 'github.com/BurntSushi/toml' component which is WTFPL so it is not actually part of our codebase.

**Comment by msohn** [comment]
What is the plan going forward ?
Do you plan to remove or replace these flagged dependencies ?
Or is there another mitigation ?

The gardener project [1] is on the way to fork kubernetes/autoscaler since we need to adapt it to machine-controller-manager [2] until machine and cluster APIs discussed in the cluster-API working group have settled and the community has agreed on common implementations.
We’d like to avoid such IP debt when forking the repository.

[1] https://github.com/gardener
[2] https://github.com/gardener/machine-controller-manager

**Comment by bgrant0607** [comment]
For ongoing enforcement, I think FOSSA is the plan.

cc @kubernetes/sig-contributor-experience-feature-requests @kubernetes/sig-testing-feature-requests

**Comment by dims** [comment]
@justaugustus can you please run a quick scan using the FOSSA to see if we still have the issues listed above? (or if any new ones show up)

**Comment by justaugustus** [comment]
@dims -- I'm on a plane at the moment and towards the end of the week on my coast. I can make sure the bits are in place and kick something off first thing next week though! :)

Also, let's tie the threads together:
- https://github.com/kubernetes/steering/issues/57 is a more up-to-date `k/steering` issue that supercedes some of the things listed here
- `k/sig-release` umbrella tracking issue: https://github.com/kubernetes/sig-release/issues/223 (which I'll bring up to date next week)

/close
