### ISSUE TITLE
License exemption for hashicorp MPL-2.0 projects

### ISSUE THREAD

**Issue by nikhita** [kubernetes/steering#210]
There are a number of projects in Kubernetes that have `github.com/hashicorp/consul` or `github.com/armon/consul-api` as a [direct/transitive dependency](https://cs.k8s.io/?q=consul&i=fosho&files=go.sum&excludeFiles=&repos=). Hashicorp's licenses are MPL and while some of their repos are blessed by CNCF as exceptions, consul is not. https://github.com/cncf/foundation/blob/master/license-exceptions/cncf-exceptions-2019-11-01.json

We should work with the CNCF GB to either get an exemption for this specific repo or get a blanket exemption for all of the hashicorp MPL-2.0 projects (preferable).

xref https://github.com/cncf/foundation/issues/138, https://github.com/kubernetes/steering/issues/57#issuecomment-458968990

**Comment by nikhita** [comment]
cc @swinslow @caniszczyk

**Comment by caniszczyk** [comment]
FYI 

"RESOLVED: That go-retryablehttp, when used in unmodified form, is approved as an exception to the CNCF Intellectual Property Policy" was recently approved by the CNCF GB and @swinslow will be updating the license exceptions.

**Comment by justaugustus** [comment]
@nikhita -- Is this one still active?

**Comment by justaugustus** [comment]
/assign @dims 
(for close message)
