### ISSUE TITLE
Clarify steering approval criteria for SIG formation

### ISSUE THREAD

**Issue by nikhita** [kubernetes/steering#214]
While converting WG K8s Infra to SIG K8s Infra (https://github.com/kubernetes/community/pull/5928), we realized that we don't have docs on whether SIG creation PRs require a simple or super majority from steering.

The current [docs](https://github.com/kubernetes/community/blob/master/sig-wg-lifecycle.md#prerequisites-for-a-wg) only specify a simple majority for WG creation.

We should create clear guidelines on the approval criteria for SIG creation as well.

/assign
Assigning it to myself to discuss, get consensus and document this

**Comment by justaugustus** [comment]
(cleaning up SC project board)
/unassign @nikhita
/help
