### ISSUE TITLE
Create guidelines for converting WG to a SIG

### ISSUE THREAD

**Issue by nikhita** [kubernetes/steering#215]
From https://github.com/kubernetes/community/pull/5928

> AFAICT, there's no documented path for conversion of a Working Group to another governance shape. It would be helpful to have future guidance on this, as I'd expect stakeholder SIGs to have input, in some form a bit stronger than simple lazy consensus.

While converting WG K8s Infra to SIG K8s Infra, we realized that we don't have docs for converting a WG to a SIG. We should have clear guidelines for this process.

/assign
Assigning it to myself but if anyone wants to take this on, please feel free to do so!

**Comment by justaugustus** [comment]
(cleaning up SC project board)
/unassign @nikhita
/help
