### ISSUE TITLE
Clarify CNCF maintainers list + Service Desk policy

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/steering#222]
### Problem Statement

Follow-up/extension of https://github.com/kubernetes/steering/issues/196.

Part of [Steering Committee onboarding](https://github.com/kubernetes/steering/blob/main/onboarding.md) (example: https://github.com/kubernetes/steering/issues/219) includes updating the CNCF maintainers lists and Service Desk access.

I think there is some confusion (at the very least on my part 🙃) on the correct grouping of users and what they should authorized to use/do.

### Proposed Solution

See "Open Questions".

### Open Questions

These should be clearly linked out in documentation.

- [ ] What is a "CNCF Maintainer" entitled to do?
- [ ] What is a CNCF Service Desk user entitled to do?
- [ ] For Kubernetes, are these the same set of users?
- [ ] Who is empowered to vote in CNCF matters on behalf of the Kubernetes project?
- [ ] Who is empowered to use the CNCF Service Desk on behalf of the Kubernetes project?

My initial take...
- CNCF Service Desk usage is separate from any CNCF "Maintainer" definition, though:
- There is a set of contributors that occupy both roles (namely @kubernetes/steering-committee) 

### Next Steps

- [ ] Document a bunch of stuff based on forthcoming conversations with Steering, @amye, and @idvoretskyi

### Other Considerations, Notes, or References

- [ ] Fixes # 
- [ ] xref #

/assign

**Comment by amye** [comment]
This is already written down, so no need to redo all of this. 
(1) Service Desk for Kubernetes is already defined here: 
https://github.com/kubernetes/steering/blob/main/service-desk.md

(2) The members of the steering committee are the authorized voting members. 

We can likely close this with that piece of documentation above added to #219.

**Comment by justaugustus** [comment]
> This is already written down, so no need to redo all of this.

Still a bit more that we'll want to do 🙃 

Based on the convo with a few Steering members, I'm hearing:
- [ ] Audit the list of existing Service Desk users
- [ ] Verify email addresses from members/leads of:
  - Steering
  - SIG ContribEx
  - SIG Release
  - SIG K8s Infra
- [ ] Prune emails from folks that are not in:
  - Steering
  - SIG ContribEx
  - SIG Release
  - SIG K8s Infra
- [ ] Update CNCF maintainers CSV to represent:
  - Voting maintainers:
    - Steering
  - Non-voting maintainers:
    - SIG ContribEx
    - SIG Release
    - SIG K8s Infra
- [ ] Update cncf-kubernetes-maintainers to distribute notifications to:
  - steering@
  - leads@

@mrbobbytables @parispittman @dims -- Can you check my work? ☝🏾

**Comment by justaugustus** [comment]
Ahhh, one more:
- [ ] Enable Steering to receive notifications for all Service Desk tickets

**Comment by mrbobbytables** [comment]
lgtm 👍

**Comment by justaugustus** [comment]
To clarify for passerbys, we're essentially delineating between:
- who can vote
- who can access CNCF Service Desk
- who gets CNCF Maintainer notifications

...which are distinct separations of concern, but groups with significant overlap.

**Comment by justaugustus** [comment]
Update the CNCF maintainers list to reflect this discussion in https://github.com/cncf/foundation/pull/229.

**Comment by idvoretskyi** [comment]
@justaugustus 

> Update cncf-kubernetes-maintainers to distribute notifications to:
steering@
leads@

We're able to add the real email addresses there only (not aliases), and our policy is that we add only folks listed in the CNCF maintainers list (maintainers.cncf.io). You are welcome to forward the necessary emails to the leads@ mailing list though :)


> Enable Steering to receive notifications for all Service Desk tickets

This is not possible with our JIRA setup, unfortunately. However, all folks under the Kubernetes team should have access to the Kubernetes tickets after logging in to the JIRA UI.

**Comment by justaugustus** [comment]
Last item from https://github.com/kubernetes/steering/issues/219:

> Add new members to the [cncf-kubernetes-maintainers](https://lists.cncf.io/g/cncf-kubernetes-maintainers) mailing list and remove emeritus members

I'll follow-up on the list of current users that Ihor sent over.
