### ISSUE TITLE
annual reports v2 dates and deadlines

### ISSUE THREAD

**Issue by parispittman** [kubernetes/steering#223]
The first edition of our Annual Reports 2020 was released very late in the year and we should do it much earlier this go around, even if some information might be overlapping. It's better to be over communicative with our needs and reports than not enough. 

We need to decide on dates and deadlines:

Jan 
 - when we, steering, need to have all policy, procedure, and process complete before chairs start - Jan 2 (merged) / ASAP 
 - dates for chairs to alert their community that the process is starting / start date - Jan 10 / or before 
 
Feb
 - PR/issue/doc draft due date - Feb 14
 -  Final date - March 1

March 
 - Draft summary for tech writer / editor review: March 15
 - Publication date on cncf.io/reports - March 30
 - retro @ chairs and tls meeting - March edition

**Comment by liggitt** [comment]
most of these were incorporated in https://github.com/kubernetes/community/pull/6295

opened https://github.com/kubernetes/community/pull/6322 to add the remaining ones
