### ISSUE TITLE
ID more roles within Steering Committee

### ISSUE THREAD

**Issue by parispittman** [kubernetes/steering#225]
### Problem Statement
At the October meeting I brought up that we should have more roles within the committee.  Bosun and liaison are our two main roles now but things fall through the cracks. These include proper ack'ing in an appropriate time period on issues, communicating changes throughout the project, and more. We also have major initiatives like code of conduct elections, annual reports, kubecon checkins, and more that need points of contact and folks to run them down. 

### Proposed Solution
We should identify roles, how they are filled, if they are rotated, etc. 
Example roles:
- PR and Issue Wrangler
- Communication Lead 
- New and Sunsetting Group On/Offboarding (or should/could be assumed by PR wrangler?)
- CNCF Liasion (or should/could this be assumed by GB rep?)

### Open Questions
- [ ] Open
- [ ] Questions

### Next Steps
- [ ] Next
- [ ] Steps

### Other Considerations, Notes, or References
- [ ] Fixes # 
- [ ] xref #

**Comment by justaugustus** [comment]
Volunteering as tribute for issue/PR wrangler + onboarding/offboarding (since I've been scanning through issues/sprucing up the project board lately)

/assign
