### ISSUE TITLE
SC Elections: Consider whether candidates should be required to meet voter requirements

### ISSUE THREAD

**Issue by jberkus** [kubernetes/steering#227]
Per the [2021 Election Retro](https://docs.google.com/document/d/1edqfsSNk_p746PcXlbHTJa8ZHNlnw3QEqNPzlVDJmUc/edit):

Currently, candidates for Steering are not required to meet voter eligibility requirements in order to run.  This has led to the odd situation in some elections where a candidate was unable to vote for themselves (or anyone else) and no such candidates have ever been elected.

The SC should consider whether being an eligible voter (whether by contributions, exception, or committee membership) should become a requirement in order to run for SC.

**Comment by justaugustus** [comment]
@kubernetes/steering-committee to leave comments (particularly @cblecker for historical context on decision)
(from 12/6 Steering public meeting)

**Comment by cblecker** [comment]
short history:
This was something that was discussed by the bootstrap committee, either that we could restrict who could run for election, or restrict who can vote.. restricting both may be unnecessary or redundant. It was originally thought that if we restrict who can vote, but leave who can run fairly open (with a small nomination bar) that we will be able to have the best folks get the job. There might be a future where the community decides they want an outside voice on the SC.

my own thoughts:
I agree with that historical precedent, even though this may create situations where a candidate can run, but not be able to actually vote for themselves.

**Comment by jberkus** [comment]
/remove-lifecycle stale

@parispittman @tpepper @liggitt @dims @mrbobbytables @parispittman any thoughts on this?   Would like a determination that we're not going to change anything.

**Comment by jberkus** [comment]
Given the inertia on this, I'm going to close it WONTFIX.

/close

**Comment by justaugustus** [comment]
/remove-lifecycle stale
/reopen

Discussed at today's Steering meeting
ref: https://docs.google.com/document/d/1qazwMIHGeF3iUh5xMJIJ6PDr-S3bNkT8tNLRkSiOkOU/edit#bookmark=id.ld1rkuodbcix, https://kubernetes.slack.com/archives/CPNFRNLTS/p1658166875780979

**Comment by jberkus** [comment]
Per discussion above, this was settled in favor of not changing the rules.  Is there some specific reason why it needs to be revisited?

**Comment by liggitt** [comment]
Discussed further in [steering slack](https://kubernetes.slack.com/archives/CPNFRNLTS/p1658166875780979).

Feedback from steering:

@cblecker:
> Thinking about it and re-reading my previous comment, I don’t think a change here is required. I’m fine with the “running for election” being different than “eligible voters” list.. especially because we still have the check where three different folks from three different employers need to endorse the candidate, and those endorsing folks need to be eligible voters themselves

@liggitt:
> I tend to agree with remaining less restrictive, especially if the only issues encountered because of the current permissive candidate requirements have been of the "that seems a little weird" variety. The "Beware the trap of SC getting to decide who can and cannot be on SC" note from the last public discussion resonated with me, since steering determines voter eligibility guidelines.

@cblecker:
> In practice, it's really only be used to consider the number of contributions to weight the wanting voters to have some “skin in the game” as it were, but still have a voting pool that is representative of the community. I think it's been fairly stable for a number of years though, so I'd be open to codifying it a bit more. But maybe that's something the elections subproject can take on?

@parispittman:
> yeah, I see this punting to elections subproject unless we can get a change we all agree to in less than ~20-25 days. may the odds be in everyone's favor until then?

@mrbobbytables:
> I agree after revisiting the historical context, regarding the voting body I think the general thought was making a change to auto-include committess and potentially sig/wg leads, those that are (potentially) not likely to have as many github recorded stats (e.g. CoCC members)

Sounds like 4/7 didn't think a change to this was needed at this time, so resolving this with no action.

/close
