### ISSUE TITLE
Docs audit

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/steering#229]
### Problem Statement

We have several documents in the Steering repo that, at the time of writing, have not been updated in multiple years.

Here are some examples:

- https://github.com/kubernetes/steering/blob/7abf985b52a75957efdca70f01671c79eca4e9d4/bosun.md
- https://github.com/kubernetes/steering/blob/7abf985b52a75957efdca70f01671c79eca4e9d4/changes.md
- https://github.com/kubernetes/steering/blob/7abf985b52a75957efdca70f01671c79eca4e9d4/cncf-and-k8s.md
- https://github.com/kubernetes/steering/blob/7abf985b52a75957efdca70f01671c79eca4e9d4/code-of-conduct.md

### Proposed Solution

- Review every doc in the repo
- Suggest changes

### Cost
If you are requesting funding please file requests issues [here](https://github.com/kubernetes/funding) , otherwise please add any associated costs with your request if it is applicable.

### Open Questions
- [ ] Open
- [ ] Questions

### Next Steps
- [ ] Next
- [ ] Steps

### Other Considerations, Notes, or References
- [ ] Fixes # 
- [ ] xref #

/assign

**Comment by justaugustus** [comment]
From @tpepper w.r.t. inclusive training requirement:

> The wording across the docs is slightly obtuse:
> - [Issue 219](https://github.com/kubernetes/steering/issues/219):
>    > All new members must complete the Inclusive Leadership Training within 30 days from the date of their appointment.
> - [Charter](https://github.com/kubernetes/steering/blob/7abf985b52a75957efdca70f01671c79eca4e9d4/charter.md#inclusive-leadership-training):
>   > Members are required to report completion of the course as part of on-boarding within 30 days from the date of their appointment.
>
> …I’m assuming the intent is the course is to be taken within the first 30 days but the charter could use a tidier sentence to be clear to what part of the sentence 30 days refers.

**Comment by justaugustus** [comment]
@kubernetes/steering-committee -- For feedback on any particular areas you'd like to see covered.

**Comment by parispittman** [comment]
#231
