### ISSUE TITLE
Private Google Drive folder for Security Response Committee

### ISSUE THREAD

**Issue by tallclair** [kubernetes/steering#236]
What's the best way to set up a private google drive folder for the Security Response Committee to use?

How would this work for committee members who's SRC email isn't a Google account?

/assign @mrbobbytables 
/cc @kubernetes/security-response-committee

**Comment by dims** [comment]
+1 from me.

**Comment by mrbobbytables** [comment]
+1 as well

**Comment by mrbobbytables** [comment]
To follow up on the actual question regarding an alternative to google drive, we don't really have one. =/ It's the preferred method of access control with full audit capabilities. Similar to the CoCC drive, permissions will be granted to the security-response-private@kubernets.io group or an alternate to-be-created group that has gmail accounts that can be granted access.

**Comment by tallclair** [comment]
Thanks all. This would be useful to us, we already have several private Google docs floating around, which makes onboarding & offboarding to the SRC a bit trickier, and I think a team drive would make the pattern a bit more robust.

Let's start by granting access to security@kubernetes.io (the canonical SRC list), and add an additional group if it turns out we need it.

**Comment by cblecker** [comment]
+1

**Comment by liggitt** [comment]
+1

**Comment by mrbobbytables** [comment]
@tallclair SRC private drive has been created (k8s-src-private - shared with security@kubernetes.io) if you could - please confirm your access and then I will remove sc3 as a manager of the drive.

**Comment by tallclair** [comment]
Confirmed. Thanks!

**Comment by mrbobbytables** [comment]
sc3 access removed, everything should be good to go! Going to go ahead and close.

/close
