### ISSUE TITLE
RFC: Spinning down / migrating Kubernetes User Groups

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/steering#241]
Kubernetes User Groups were intended to serve as rallying points for spaces in the Kubernetes ecosystem that did not directly align with the scope of a SIG or WG. They were to facilitate communication between users and upstream, publish best practices in their focus area etc.

While the intent was sound, user groups have not seen much adoption within the Kubernetes upstream community directly with only two listed as part of the project ([ug-big-data](https://github.com/kubernetes/community/tree/master/ug-big-data), [ug-vmware-users](https://github.com/kubernetes/community/tree/master/ug-vmware-users)), and only one decently active. Instead, their verticals have flourished in the greater Cloud Native ecosystem in the form of other foundations, CNCF TAGs, WGs and their own End User Groups.

In an effort to streamline governance and turn down services that aren't actively being used, we (steering) would like to spin down or relocate the user groups to the CNCF or other appropriate homes.

**Comment by parispittman** [comment]
+1

**Comment by parispittman** [comment]
@caniszczyk and/or @dims where should this convo start? TOC or another venue?

**Comment by caniszczyk** [comment]
I think first spin down what isn't needed anymore and update k8s governance to not have UGs anymore?

I don't think we need for formalize most of these into something more inside of CNCF where the TOC approves them, but maybe @dims has other thoughts since he's closer to these things than I am. We can always setup a slack channel for these UGs if they want to live on in the CNCF slack unofficially

**Comment by mrbobbytables** [comment]
@caniszczyk - yeah, this is a starting point for discussion. We'd update governance to remove them.

IMO  - I don't think its a TOC thing either, they'd goto the End User Advisory Community (but I don't think that exists anymore... :x) and then form an End User Group (e.g. the [research user group](https://github.com/cncf/research-user-group)) if they wanted to continue to exist in a more official capacity.

@onlydole what are your thoughts?

**Comment by onlydole** [comment]
Howdy, howdy! 👋🏼 😄

This is a great point - I agree that it makes sense to close down the user groups that do not want to continue and add interested user groups to be housed in the CNCF vs. the Kubernetes community (wherever it makes sense). 

If they are able to provide a charter and [some other information](https://github.com/cncf/foundation/blob/8e10117c1c16a2851319854135318775967ee626/cncfgroups.md) that would be incredibly helpful! 

I'm still learning how groups are formed and sponsored on the CNCF side, though I'm happy to jump on calls or discussions with anyone that'd be interested in these changes! :smile:

**Comment by jberkus** [comment]
Hey, waking up this issue.

UG Big Data is dead.  There is no conversation in its slack for months, there hasn't been a meeting in 2 years.  I talked to one of the leads (Eric) and he agreed that it was time to shut down the UG.

So out of the two UGs, that's one we can just shut down.

**Comment by BenTheElder** [comment]
Big Data was archived in https://github.com/kubernetes/community/pull/7046, The VMware User Group remains.

**Comment by mrbobbytables** [comment]
This was done some time ago, closing the loop 👍 
/close
