### ISSUE TITLE
Community Annual Report Feedback

### ISSUE THREAD

**Issue by parispittman** [kubernetes/steering#242]
https://www.cncf.io/reports/kubernetes-annual-report-2021/ 

steering public retro - Monday, June 6 @ 930am PT / 430pm UTC

***Community Retro***
_answer in comments_

1. What can we do better?

2. Is the report valuable? How can we add more value?

3. What did you like about it? 

4. additional comments/suggestions/ways you can help out? 

Comment below!

**Comment by parispittman** [comment]
we buried the lede on areas that have single maintainer or really close; figure out how to get that to the top next time

**Comment by parispittman** [comment]
we're going to put a description together for an intern to help us with automation to cut down the time to prepare and to gather the summary information down to a few months from several. goal - 7 to 3.5 months 

some of the scope is here but not the summary pieces:
https://github.com/kubernetes/community/issues/6357

**Comment by parispittman** [comment]
feedback from chairs and tech leads meeting:
Overall 
many sigs enjoyed a dedicated time to refine roadmap 
folks though template was good this year 
Covid may had an impact and the report helps with getting data and pulling people together to get measurements 
creating calls to actions are good
Greater visibility on OWNERS helps start conversations with OWNERS and check

challenges about the process?
Contributing.md - many SIGS don't have this up to date; hard to maintain and keep up to date 
some sigs spent a lot of time here (on contributing guide development) and was actually great 
Continue with template/swiss cheese holes with kep reporting 

things we should do/ask for next time?
Gap analysis stuff ‘where is your group now and where do you want to be’
Better refine questions so that the requests are useful 
Code owning sigs vs non code owning sig questions 
What is a package 
be more mindful of how we ask questions (‘if you own code, or is there some equiv metric’); help us understand goal of question
use a chair/tech lead meeting as a working session

**Comment by amcasari** [comment]
If SIGs want focused help to improve their contributing docs, @glasnt and I have some frameworks that might help (and could schedule time in Q3-Q4).
