### ISSUE TITLE
DMARC failing on kubernetes.io

### ISSUE THREAD

**Issue by chris-short** [kubernetes/steering#243]
### Problem Statement
kubernetes.io has no DMARC configuration. This is sending legitimate emails to spam folders potentially globally. You can check here: https://mxtoolbox.com/SuperTool.aspx

A release candidate email in my spam folder is what triggered this

### Proposed Solution
I believe the Google Admin console can generate these on steering's behalf, but if there's any confusion (email is hard), I'm an admin on my own domain; happy to help out.

The guide is pretty straightforward though: https://support.google.com/a/answer/2466580?product_name=UnuFlow&hl=en&visit_id=637867479928607575-3291798451&rd=1&src=supportwidget0&hl=en

### Cost
$0.00

### Open Questions
- [ ] Open
- [ ] Questions

### Next Steps
- [ ] Next
- [ ] Steps

### Other Considerations, Notes, or References
- [ ] Fixes # 
- [ ] xref #

**Comment by liggitt** [comment]
just to clarify, it was kubernetes.io and not kubernetes.dev?

**Comment by chris-short** [comment]
Correct. I've not had enough coffee yet.

*Chris Short* <https://linktr.ee/TheChrisShort>
He/Him/His
TZ=America/Detroit

**Comment by liggitt** [comment]
Slack discussion context:
* https://kubernetes.slack.com/archives/C1TU9EB9S/p1651143073035419
* https://kubernetes.slack.com/archives/C1TU9EB9S/p1651151246058179

**Comment by liggitt** [comment]
/assign @dims @parispittman @mrbobbytables 
per https://github.com/kubernetes/steering/#google-workspace

is there any downside/disruption possibility as a result of setting up DMARC?

**Comment by liggitt** [comment]
looks like this requires DNS config, right? which would be defined the same way the SPF record is, in https://github.com/kubernetes/k8s.io/blob/main/dns/zone-configs/k8s.io._0_base.yaml#L36 ?

**Comment by chris-short** [comment]
Where is SendGrid in this puzzle?

**Comment by dims** [comment]
thanks for digging in @mrbobbytables and @chris-short - looks like we a no-op for now.

**Comment by mrbobbytables** [comment]
Sadly not much we can really do about this at this point. =/
Going to go ahead and close for now.

/close
