### ISSUE TITLE
Iterate on charter changes around committee membership/elections

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/steering#250]
### Problem Statement

https://github.com/kubernetes/steering/pull/248 and https://github.com/kubernetes/steering/pull/249 propose charter changes related to the elections process and committee membership.

In presenting these changes, we've received a lot of useful feedback that would likely be best handled in separate PRs.

### Proposed Solution

- Use https://gist.github.com/justaugustus/7c4742225481247f99685918400a5cd5 as a guide to what changes were proposed in https://github.com/kubernetes/steering/pull/248
- Sweep and group all review feedback by section
- Issue individual change PRs by section/theme

### Cost

If you are requesting funding please file requests issues [here](https://github.com/kubernetes/funding) , otherwise please add any associated costs with your request if it is applicable.

### Open Questions

- [ ] Open
- [ ] Questions

### Next Steps

- [ ] Next
- [ ] Steps

### Other Considerations, Notes, or References

- [ ] Fixes # 
- [ ] xref #

**Comment by jberkus** [comment]
One follow-up is "how we replace empty seats" which needs further development beyond what we've already merged.

**Comment by jberkus** [comment]
Second task (for the Elections Subproject): create the rules for conducting a special election, including how EOs are chosen and timelines.
