### ISSUE TITLE
Collect usage metrics for minikube 

### ISSUE THREAD

**Issue by medyagh** [kubernetes/steering#259]
### Problem Statement
Per conversation with @mrbobbytables creating this issue.

Minikube has a lot of commands, sub commands and features/drivers, container runtimes and features on a matrix of OS and CPU Architectures, but unfortunately we do not have any metrics that tells us what drivers/container runtime or which minikube commands are being used most by the users, which makes it hard to decide what features or drivers or runtimes to invest or which ones to deprecate.

### Proposed Solution

Collect usage metrics for basics commands of minikube on which commands get invoked and which commands have highest non-zero exit codes, and also other metrics such as operating system and CPU architecture and so on.

### Cost
N/A

### Open Questions
- [ ] Open
- [ ] Questions

### Next Steps
- [ ] Next
- [ ] Steps

### Other Considerations, Notes, or References
- [ ] Fixes # 
- [ ] xref #

**Comment by BenTheElder** [comment]
Discussed at Today's Steering Meeting.

Immediate Action Items:
- Open LF Service Desk ticket to ask about prior art under the LF / Approved tools
- Reach out to groups with possible prior art within the project

/assign

Possible related prior art within the project:
- Kubernetes SIG K8s Infra k8s.gcr.io data with II.coop
- Google Analytics (I think?) on Kubernetes docs under SIG Docs
- https://github.com/kubernetes-retired/spartakus (though @mrbobbytables thinks it never really wound up being used much if at all)

**Comment by medyagh** [comment]
> * ith possible prior art within the project

Thanks Ben, are these action items for us or has anyone been assigned to it ?


on the Website analytics I have created this issue, waiting for reply https://github.com/kubernetes/website/issues/37801

**Comment by BenTheElder** [comment]
Those action items were meant for me to handle, with my steering hat 😅 

I'll be following up more later this week, happy to have help! The CNCF service desk is currently open to their listed official maintainers which for Kubernetes is steering, so I'll have to do that one (will file within the week and report back).

**Comment by BenTheElder** [comment]
Last week I got access to the service desk, today I filed CNCFSD-1530.

**Comment by BenTheElder** [comment]
Service Desk Response:
> Thank you for logging this request.
> 
> We do not have any prior art that we recommend to gather telemetry.
> 
> If the Minikube project were to gather telemetry on command usage then any implementation would have to comply with the following Linux Foundation Policy
> 
> https://www.linuxfoundation.org/legal/telemetry-data-policy
> 
> Data collection is complicated by the need to be in compliance with regulations around the world, such as, but not limited to, the EU’s GDPR. So we think it would take a long time to review.
> 
> I have reached out to the Privacy Team to get copies of the two submissions and reviews that appear on the bottom the above policy document and I will share their response with you when it comes in.

**Comment by RobertKielty** [comment]
I did some more digging on this and have come up with the following reference that will probably be useful to research this topic further.

https://cd.foundation/blog/2020/04/09/spinnaker-1-18-spinnaker-community-stats/

Lot's of useful information there, in particular :

> All stats collection code is open source and can be found in the [Spinnaker stats](https://github.com/spinnaker/stats), [Echo](https://github.com/spinnaker/echo/blob/master/echo-telemetry/src/main/java/com/netflix/spinnaker/echo/telemetry/TelemetryEventListener.java), and [Kork](https://github.com/spinnaker/kork/blob/master/kork-proto/src/main/proto/stats/log.proto) repos found on GitHub.

**Comment by dims** [comment]
fyi there's a LF level policy - https://www.linuxfoundation.org/legal/telemetry-data-policy
