### ISSUE TITLE
Logo for Kueue, subproject of SIG Scheduling

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/steering#264]
### Problem Statement

We need a logo for kueue

### Proposed Solution

Request to CNCF

### Next Steps
- [ ] Open a ticket https://github.com/cncf/servicedesk#design-and-aesthetics

### Other Considerations, Notes, or References

- [ ] xref https://github.com/kubernetes-sigs/kueue/issues/377
- This is the high level idea that we have
![image](https://user-images.githubusercontent.com/1299064/212978935-69730189-cfff-4a94-ad03-e38c0311199f.png)

**Comment by mrbobbytables** [comment]
@alculquicondor The CNCF has some docs to get started with refining the logo - template and details can be found here:
https://github.com/cncf/foundation/tree/main/documents

**Comment by moficodes** [comment]
@mrbobbytables is there a specific place to send the completed template?

**Comment by mrbobbytables** [comment]
if you can link it here, I can update the service desk ticket with the link 👍

**Comment by moficodes** [comment]
https://gist.github.com/moficodes/06c9190c8ffdf3411212db7e467c9d52

**Comment by moficodes** [comment]
@mrbobbytables

**Comment by kerthcet** [comment]
A trivial though, different shades of colors to represent different types of jobs or variety priorities. 🙃

**Comment by alculquicondor** [comment]
I like the idea. @mrbobbytables did you sent the request already or can we update the gist?

**Comment by mrbobbytables** [comment]
I did, but I don't think any work has started yet, I'd go ahead and update the gist

**Comment by mrbobbytables** [comment]
Here are the mock ups, let me know which one(s) you like and can give feedback to the CNCF 
[kubernetes-kueue-logo_v1.pdf](https://github.com/kubernetes/steering/files/10769068/kubernetes-kueue-logo_v1.pdf)

**Comment by kerthcet** [comment]
Thanks @mrbobbytables that was excellent.

**Comment by moficodes** [comment]
Hey @mrbobbytables 
The community liked this design the best. 
<img width="272" alt="Screenshot 2023-03-13 at 2 50 20 PM" src="https://user-images.githubusercontent.com/14829780/224800855-5b74f4a2-315f-476d-a3ac-b02a4b842944.png">

We have couple of changes we would like to request.

1. The color. Could we use #326ce5 as the base color (same as the k8s logo)?
2. The shape of 4 triangles. Could we make the triangles a bit more rounded?

**Comment by mrbobbytables** [comment]
Here is round 2 of updates:
[kubernetes-kueue-logo_v2.pdf](https://github.com/kubernetes/steering/files/11045596/kubernetes-kueue-logo_v2.pdf)

**Comment by alculquicondor** [comment]
Awesome. I'd like to go with the 2nd option:

![image](https://user-images.githubusercontent.com/1299064/227216678-728aff5b-ecae-4ff5-8975-b797c449e4ff.png)

**Comment by alculquicondor** [comment]
@mrbobbytables is there anything else remaining for this?

We have been using the logo from the pdf, but it was my understanding that we would receive an .svg file?

**Comment by alculquicondor** [comment]
oh, awesome!

Thanks!

/close
