### ISSUE TITLE
V2 Contributor Badge

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/steering#265]
### Problem Statement

Historically Kubernetes has as a project given out a special Kubernetes patch to contributors of all kinds as a form of recognition, e.g. mailed to contributors or handed out at the contributor summit. This patch was ~exclusively available to recognized contributors. 

At KubeCon EU @eddiezane reported they were available for $3 in a bucket at checkout in the CNCF swag store, which devalues the contributor recognition angle. Previously spotting someone wearing this badge on their bag strongly suggested they'd been contributing to the project and was a nice way to bump into other traveling contributors. It also felt rewarding to receive one as a small token of appreciation from the project.

Ideally we'd have something clearly recognizable for contributors that wasn't positioned as general swag.

### Proposed Solution

I personally suggest we make some clear reference to contributing in the design of a new badge/pin/... to self-select for contributors without needing any sort of gate-keeping, though we should also clearly request that these not be placed cheaply at checkout.

We've previously done our own contributor conference swag, with unique designs each time, but not everyone can attend these and the designs imply attending even if we mailed out more of them. I think we want to continue those but they don't quite cover this.

### Cost
> If you are requesting funding please file requests issues [here](https://github.com/kubernetes/funding) , otherwise please add any associated costs with your request if it is applicable.

N/A for now. Potentially some cost to produce etc later.

### Open Questions
- [ ] What exactly do we want?
   - Probably a fabric badge again? I think the format was popular. 
- [ ] How would we accomplish distributing them again? Previously we've accomplished the bulk of distribution through conferences with supplemental mailed patches but fewer members are able to attend these days.
- [ ] Who can/should design this?

### Next Steps

- [x] Seek general feedback 
  - (see slack #krafterenetes, mailinglists, here ...)
- [x] Reach out to CNCF
  - https://github.com/kubernetes/steering/issues/265#issuecomment-1720063423

### Other Considerations, Notes, or References
- Original slack thread: https://kubernetes.slack.com/archives/CPNFRNLTS/p1682080801704139
- See also somewhat related: https://github.com/kubernetes/steering/issues/263

**Comment by jberkus** [comment]
I've put a request out on Krafternetes channel to see if anyone is into designing something.  Staff have let me know that this will be a lot faster if we supply the design.

**Comment by jberkus** [comment]
If folks want to discuss ideas for badge designs, join the #krafternetes channel on Slack.

**Comment by thockin** [comment]
The big patch was...big.  Maybe we should aim for something a little more subtle - more like a "secret society" than SWAG?

Like, would a small, simple, elegant "lapel pin" fit the bill?  Think like a 3/4" polished stainless steel heptagon with no words.

**Comment by parispittman** [comment]
this is why i created the pins. can we use those?

**Comment by thockin** [comment]
I don't think I have seen the Heptio ones.  I have a few "regular" pins - I was thinking something somewhat more reductive and higher "perceived quality".  Like, it doesn't actually need to be platinum, but if you told people it was they might believe you.

**Comment by palnabarun** [comment]
IIRC, some Kubernetes pins were floating around a few years prior. I didn't see many of them, but they looked premium.

**Comment by pacoxu** [comment]
> Per early discussions: I'll open a service desk ticket with CNCF as steering when the project has settled on artwork. Then they should be able to get badges printed for Chicago / Contributor Summit NA '23 to start.

There seem to be no contributor summit in Shanghai Kubecon this Sept.😓

**Comment by BenTheElder** [comment]
See also: This thread in #krafternetes slack.k8s.io https://kubernetes.slack.com/archives/C02LM67B3GA/p1686689129392819

**Comment by jberkus** [comment]
@pacoxu we've been looking for someone to lead one in China.  Unfortunately, few contributors from outside China will be able to travel there this year.  If you know anyone who's interested in running a mini contributor summit, we can help them get it set up.

**Comment by pacoxu** [comment]
> @pacoxu we've been looking for someone to lead one in China. Unfortunately, few contributors from outside China will be able to travel there this year. If you know anyone who's interested in running a mini contributor summit, we can help them get it set up.

Yes, there are only a few contributors in China, and since few contributors from outside China will come, the summit may be too big an activity. Probably, we can have mini [**SIG Meet and Greet**](https://kccnceu2023.sched.com/event/1Iqwl/kubernetes-project-sig-meet-and-greet) like the one in Amsterdam.

The `Meet and Greet` can invite both SIGs and WGs, new and experienced contributors.
For developers who want to make some contributions in the future, experienced Kubernetes contributors(approvers/reviewers) may share experiences in SIGs and WGs, and how to get involved.

**Comment by kevin-wangzefeng** [comment]
Just to add that some of the SIG contributors may not code in upstream, but if we can have the event, people will come.
Maybe we can have a survey to help making decision, or we can just run it in the [Unconference](https://en.wikipedia.org/wiki/Unconference) way.

**Comment by mrbobbytables** [comment]
@cpanato it'd be all active members. Essentially anyone at a contrib summit

**Comment by josh-ferrell** [comment]
@mrbobbytables it'd be awesome to be able to get a pin/patch out to contributors that couldn't make it to a contributors summit if they covered S&H.

**Comment by parispittman** [comment]
@josh-ferrell that's who i was thinking of when writing https://github.com/kubernetes/community/issues/6492

could easily set up a code for the swag store after membership or promotion into an owners file, you get a code to go and claim it with shipping and handling included

**Comment by mrbobbytables** [comment]
@josh-ferrell we have made the patches available through the cncf store that folks could get it shipped to them with a code. 

The summits are really just our main distribution mechanism.

**Comment by josh-ferrell** [comment]
> @josh-ferrell we have made the patches available through the cncf store that folks could get it shipped to them with a code.
> 
> The summits are really just our main distribution mechanism.

Didn't realize that, very cool

**Comment by BenTheElder** [comment]
Folks, contributor summit hosting / venues is rather off topic for this issue, can we please use this one to discuss what sort of pin/badge we want to distribute to contributors and discuss when/where contributors summits are hosted in a different issue/thread? Thanks.

-----

Also yes, as referenced further back even in the original issue body text we've used the contributor summit to cheaply mass distribute to contributors but it has never been the only distribution mechanism and we'll be sure to make sure to include folks that can't make it.

That's also why the individual summit specific themed swag is not suitable for this role, e.g. at detroit we had cool detroit themed contributor summit jackets but those are oriented around the event and not more generally contributing, and not everyone can attend these.

We should continue to offer both, and here we're looking to reboot the general non-event-specific contributor badge (or perhaps replace it with something else like a pin).

I also like the idea of a pin, there's some very interested discussion in the thread linked in https://github.com/kubernetes/steering/issues/265#issuecomment-1592126999

**Comment by BenTheElder** [comment]
> heptio passed out plain pins with no words for a few years so the community could be saturated with those by now. i have a few. i liked having a word on there for this reason.

+1, I also think having something like "contributor" on them automatically avoids "hmm i'll just buy one of these because it looks cool and I like Kubernetes.

> I don't think I have seen the Heptio ones. I have a few "regular" pins - I was thinking something somewhat more reductive and higher "perceived quality". Like, it doesn't actually need to be platinum, but if you told people it was they might believe you.

I have the heptio pins and they're pretty high quality metal + enamel pins of the logo(s) IIRC, I don't think we could outdo those but we could just use a different design (e.g. flat metal instead of colored enamel).

**Comment by BenTheElder** [comment]
heptio kubernetes pin for reference:
<img src="https://github.com/kubernetes/steering/assets/917931/4c388d87-0f52-4523-8f7c-ab6f2a17167f" width="500px" alt="picture of enamel kubernetes logo pin">

`/approve` pin:
<img src="https://github.com/kubernetes/steering/assets/917931/0b18d3ef-561d-4b30-a914-e92807b859d2" width="500px" alt="picture of enamel /approve pin">

The `/approve` pin I think was the https://github.com/kubernetes/community/issues/6492 reference given out to approvers in OWNERS during at least one contributor summit so far?

**Comment by jberkus** [comment]
@pacoxu please contact me in SIG-Contribex slack channel. Same ID.  Thanks.

**Comment by kaslin** [comment]
I've filed a service desk ticket for contributor pins as discussed in the #krafternetes channel on Slack. Mock up attached. Variants like "lead" and "steering" were discussed, but working on the "contributor" variant first.
![ContributorPinDesign_BronzeShiny](https://github.com/kubernetes/steering/assets/5102554/07ac97ca-c894-4f07-a4e6-3f4a04c6b8b7)

**Comment by thockin** [comment]
Kaslin, can you link to that one vendor we found, which shows what the two tones in your mock mean?  I lost the link, do you have it?

**Comment by kaslin** [comment]
Yes! I also referenced it in the service desk request.
https://wizardpins.com/products/sandblast-pins
https://wizardpins.com/products/antique-pins

Also I'm thinking of requesting an order similar to t-shirts for the contributor summit. I'm not sure how stock should be maintained beyond KubeCon. If anyone has any context or ideas on that, I would appreciate it.

**Comment by BenTheElder** [comment]
Thank you again @kaslin for the excellent design and @thockin for making sure we got a rush order in time for KubeCon when CNCF was too overloaded / too close to the conference.

These are awesome, and we'll continue to get these out to people at future events.

<img src="https://github.com/kubernetes/steering/assets/917931/6f5fe481-bc04-45d7-87c2-dc1ccb54bf27" width="200">

**Comment by coolme22** [comment]
We can help you solve this problem https://www.coolwholesales.com/
