### ISSUE TITLE
Election Officers for 2023 for Approval

### ISSUE THREAD

**Issue by jberkus** [kubernetes/steering#268]
The Elections Subproject* has selected the following Election Officers to recommend for running this year's Steering Election:

Officers:

- Kaslin Fields
- Davanum Srinivas
- Bridget Kromhout

Alternates:

- Christoph Blecker
- Lachlan Evenson

This includes an increase in the number of alternates from one to two; this is both for extra redundancy because folks lives have been unpredictable this year, and to ensure that we have an adequate number of experienced EOs next year.

Please approve by Steering vote in this issue; we cannot proceed further until you do.

/committee steering
/area elections
/priority important soon

(* current voting members: @jberkus, @fsmunoz, @parispittman, @mrbobbytables, @nikhita)

**Comment by cblecker** [comment]
I am happy to be named an alternate as I am not eligible to run in this election.

However, with my steering hat on I will abstain from this vote as it applies to me personally.

**Comment by mrbobbytables** [comment]
lgtm with steering hat

**Comment by BenTheElder** [comment]
LGTM with steering hat

**Comment by tpepper** [comment]
LGTM w/ steering hat on

**Comment by palnabarun** [comment]
LGTM with my steering hat

**Comment by cpanato** [comment]
LGTM with the steering hat

**Comment by jberkus** [comment]
I count 5 steering votes in favor.  I'll prepare the PRs/messaging now.
