### ISSUE TITLE
Document what working groups are, and how to form and disband

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/steering#27]
- Update docs to describe relationship with SIGs

**Comment by jdumars** [comment]
WIP: https://docs.google.com/document/d/1AlI89KijzO9_KAqUX_pbumgld1LN0tte2FMdjLw83wY/edit 

Please comment.

**Comment by spiffxp** [comment]
/assign @philips @derekwaynecarr @spiffxp

Discussed during 2018-07-18 meeting, the four of us will work to review and push into a PR to be merged by next steering meeting

**Comment by spiffxp** [comment]
/unassign @philips 
/assign @jbeda 
got my wires crossed

**Comment by jdumars** [comment]
As a follow-up, we probably need to fix existing mis-classified WGs, etc. per this: https://www.google.com/url?q=https://groups.google.com/a/kubernetes.io/d/msg/steering/zEY93Swa_Ss/C0ziwjkGCQAJ&sa=D&ust=1532010011381000&usg=AFQjCNGbTyXk1IeMristsoaqKIo5t-OFiA

**Comment by jdumars** [comment]
Discussed 20180718: https://youtu.be/I6BwkOA9dn4?t=42m56s

**Comment by spiffxp** [comment]
Merged https://github.com/kubernetes/community/pull/2173

**Comment by spiffxp** [comment]
This remains undone, I can tackle PR'ing this later this week

**Comment by derekwaynecarr** [comment]
@spiffxp please send note when pr is opened and would love to review.

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/community/pull/2702

We appear to have hit a difference of opinion from @brendandburns

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/community/pull/2814
ref: https://github.com/kubernetes/community/pull/1994

I'm re-titling this because it seems like scope has grown beyond just creating a working group.

**Comment by spiffxp** [comment]
OK, what's keeping this open?  AFAICT it's:
- https://github.com/kubernetes/community/issues/2766 - document that working groups may own code in an associated repo
- https://github.com/kubernetes/community/issues/2176 - add a field to sigs.yaml that can list the specific sigs a wg spans

**Comment by philips** [comment]
I believe #2766 was addressed @spiffxp so I closed it.
