### ISSUE TITLE
Update Steering members following 2023 election cycle

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/steering#273]
# Steering Onboarding

This document covers steps needed to onboard new Steering Committee
members and off-board emeritus members.

_NOTE(@justaugustus): These items were initially copied from https://github.com/kubernetes/steering/issues/256. I'll be reviewing and cleaning up this list as we action on the items._

## Initial steps

- [x] All new members must complete the [Inclusive Leadership Training]
within 30 days from the date of their appointment.
  - [x] @justaugustus certificate ID number: [LF-zhwaqh4h1z]()  from https://github.com/kubernetes/steering/issues/219
  - [x] @pacoxu certificate ID number: [LF-5l8akc7m1l](https://ti-user-certificates.s3.amazonaws.com/e0df7fbf-a057-42af-8a1f-590912be5460/f744b703-3b63-4fc7-bbcb-a1c7e3f2da3f-paco-xu-f0898ae0-f703-47d1-b8f6-aac0a7204b37-certificate.pdf)
  - [x] @pohly certificate ID number: [LF-wzi8mgvbjy](https://ti-user-certificates.s3.amazonaws.com/e0df7fbf-a057-42af-8a1f-590912be5460/f579b149-5faf-42fa-9ced-5147cd8de7e5-patrick-ohly-04fa408d-a46c-4f67-a4c2-fa33aaac4328-certificate.pdf)
  - [x] @soltysh certificate ID number: [LF-7d267jryh6](https://ti-user-certificates.s3.amazonaws.com/e0df7fbf-a057-42af-8a1f-590912be5460/56f13280-c256-4a15-bf15-aca4dfc9bed8-maciej-szulik-607b5155-e18f-4397-8d34-f5d467bea8d4-certificate.pdf)
- [x] Update the following files in the respective repos:
  - [x] [kubernetes/steering]: `OWNERS_ALIASES` and `README.md`: https://github.com/kubernetes/steering/pull/274
  - [x] [kubernetes/community]:
    - [x] `sigs.yaml` (SC members and liaisons) and auto-generated content: https://github.com/kubernetes/community/pull/7558
    - [x] Slack usergroup - `communication/slack-config/usergroups.yaml`, `communication/slack-config/users.yaml`: https://github.com/kubernetes/community/pull/7558
  - [x] [kubernetes/org]: `OWNERS_ALIASES` and the `steering-committee` GitHub team: https://github.com/kubernetes/org/pull/4497
  - [x] [kubernetes/website]: `OWNERS_ALIASES`: https://github.com/kubernetes/website/pull/43296
  - [x] [kubernetes/funding]: `OWNERS_ALIASES`: https://github.com/kubernetes/funding/pull/41
  - [x] [kubernetes/k8s.io]: 
    - [x] Update steering@kubernetes.io, steering-private@kubernetes.io, and steering-emeritus@kubernetes.io in `groups/groups.yaml`: https://github.com/kubernetes/k8s.io/pull/5918
    - [x] `OWNERS_ALIASES`: https://github.com/kubernetes/k8s.io/pull/5918
- [x] Add new members to the `steering-private` and `steering-gb-rep-private` Slack channels
- [x] Add new members to the CNCF Service Desk and remove Emeritus members
  - [x] @justaugustus
  - [x] @pacoxu
  - [x] @pohly
  - [x] @soltysh
- [x] Add new members to the [cncf-kubernetes-maintainers] mailing list and remove Emeritus members
  - [x] @justaugustus
  - [x] @pacoxu
  - [x] @pohly
  - [x] @soltysh
- [x] Add new members to the [Public CNCF Maintainer List] and remove Emeritus members: https://github.com/cncf/foundation/pull/643
- [x] Transfer Community Group [liaison assignments] from Emeritus members to new members: https://github.com/kubernetes/community/pull/7560
- [x] (N/A) If a Google Workspace [top-level account] is owned by an emeritus member,
transfer it to an existing member
  - Currently owned by @justaugustus, @palnabarun, and @mrbobbytables
- [ ] If an Emeritus member is one of the @kubernetesio Twitter account contributors,
transfer access to an existing member
- [x] If [Zoom license credentials] were owned by a majority of Emeritus
members, share them with existing members. The Zoom host key is
accessible to all members and is a pinned message in the `steering-private`
slack channel
- [x] Add new members to 1Password, remove emeritus members
- [x] Set up a private meeting to go over backlog

### After handoff meeting

- [x] Remove Emeritus members from the `steering-private` and `steering-gb-rep-private` Slack channels

### Follow-up items

- [x] Consider new time for public/private Steering meetings ([example](https://www.timeanddate.com/worldclock/meetingtime.html?month=10&day=3&year=2023&p1=224&p2=77&p3=179&p4=262&p5=37&p6=176&p7=33&iv=0))
- [ ] Update and convert onboarding documentation into issue template

---

I'll take point on the PRs:
/assign @justaugustus
cc: @pacoxu @pohly @soltysh

[Inclusive Leadership Training]: https://github.com/kubernetes/steering/blob/main/charter.md#inclusive-leadership-training
[kubernetes/steering]: https://github.com/kubernetes/steering
[kubernetes/community]: https://github.com/kubernetes/community
[kubernetes/org]: https://github.com/kubernetes/org
[kubernetes/website]: https://github.com/kubernetes/website
[kubernetes/funding]: https://github.com/kubernetes/funding
[kubernetes/k8s.io]: https://github.com/kubernetes/k8s.io
[liaison assignments]: https://git.k8s.io/community/liaisons.md
[cncf-kubernetes-maintainers]: https://lists.cncf.io/g/cncf-kubernetes-maintainers
[Public CNCF Maintainer List]: https://github.com/cncf/foundation/blob/master/project-maintainers.csv
[top-level account]: https://github.com/kubernetes/steering/README.md#top-level-accounts
[Zoom license credentials]: https://github.com/kubernetes/steering/README.md#zoom-admins

**Comment by BenTheElder** [comment]
Seems like we should close this out ...?

**Comment by BenTheElder** [comment]
Closing this, and acknowledging the two remaining unchecked tasks:

> If an Emeritus member is one of the https://github.com/kubernetesio Twitter account contributors,
transfer access to an existing member

We've moved this to 1password with SIG Contributor Experience Contributor Comms team, so this is N/A now.

>  Update and convert onboarding documentation into issue template

I think we can punt anything further here to next time now.

/assign
/close
