### ISSUE TITLE
request: recurring ~$3000USD D&O Insurance

### ISSUE THREAD

**Issue by parispittman** [kubernetes/steering#278]
- **Description**: 
Requesting [Directors and Officers](https://www.investopedia.com/terms/d/directors-and-officers-liability-insurance.asp) Insurance for Steering Committee, Code of Conduct Committee, and Security Response Committee members.
https://www.kubernetes.dev/community/community-groups/#committees 
19 total members

    Referrals / Recs / Other:
    1 Thomas S. Pappas, MSA, CNAP | Senior Consultant | Virtual, Inc. - ASF
    2 https://docs.opencollective.foundation/what-we-offer/liability-insurance - offers a flat rate of $600

 

  
- **Requesting SIG**:
s/sig/committee: steering 

  
 
- **SIG approval**: 
collecting approvals on this chain
  
 
- **Cost**:
We will need to get proper quotes from CNCF folks. Here's what the broad range is:

    1
    "under 3k a year"
     https://www.insureon.com/small-business-insurance/directors-officers/cost 

    2
     https://www.embroker.com/blog/directors-and-officers-insurance-cost/ 
Funding | Limits | Retention | Premium
-- | -- | -- | --
$0 – 10M | $1 – 2M | $10 – 25k | $3.5 – 6k
$10 – 25M | $2 – 3M | $10 – 50k | $5 – 10k

  - Frequency:
yearly?
 
  - Scale function: 

     unsure - will need to research when we get actual quotes 

  

- **owner of cancellation/renewal**
cancellation - steering
renewal - hopefully automatic; cncf  

  
- **Alternatives considered**:

alternatives are no insurance or individuals insuring themselves, which is where we are today

**Comment by BenTheElder** [comment]
As I understand it: This was raised to the CNCF and the responses are largely public in https://github.com/cncf/foundation/issues/329 (I've looked back over the service desk ticket).

We should probably close this in favor of https://github.com/cncf/foundation/issues/329
