### ISSUE TITLE
Proposal: Enable gitvote for steering repo

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/steering#282]
### Proposal

Currently, when steering votes on an issue they make some sort of comment along the lines of "+1 with steering hat on". 
This _does_ work and is suitable for most scenarios, however [gitvote](https://github.com/cncf/gitvote) as used by the CNCF's TOC looks like a better solution ([example vote](https://github.com/cncf/toc/issues/1151#issuecomment-1687065712)) with some handy functionality like being able to [check status](https://github.com/cncf/toc/issues/1151#issuecomment-1690874266), post [weekly vote updates](https://github.com/cncf/toc/issues/1151#issuecomment-1707272724) etc.

This could potentially be enabled for the community repo for various charter votes or other instances where a SIG or group would like to call a public vote.

/committee steering

**Comment by BenTheElder** [comment]
It looks like the CNCF is centrally hosting this so we don't need to run anything?

**Comment by mrbobbytables** [comment]
> It looks like the CNCF is centrally hosting this so we don't need to run anything?

Yup! No need for us to run anything. 👍

**Comment by justaugustus** [comment]
+1!

**Comment by justaugustus** [comment]
I've just configured gitvote for TODO Group Steering.
Linking the tracking issue here as a reference point: https://github.com/todogroup/governance/issues/326

**Comment by BenTheElder** [comment]
Explicit +1.

cc @kubernetes/steering-committee please comment +1 / -1.

If we enable this we can switch to 👍  /  👎 on the issue body for future issues.

**Comment by pacoxu** [comment]
+1

**Comment by palnabarun** [comment]
+1 (steering)

**Comment by mrbobbytables** [comment]
gitvote has now been enabled for this repo, we'll need to [configure it](https://github.com/cncf/gitvote?tab=readme-ov-file#configuration) before it can be used however.

I would also suggest enabling it on the community repo so that charter changes etc can be easily checked.
