### ISSUE TITLE
Charters Meta-issue

### ISSUE THREAD

**Issue by jdumars** [kubernetes/steering#31]
This issue is to help organize the work necessary to move SIG/WG charters forward.

[Tracking spreadsheet that was the source for this issue](https://docs.google.com/spreadsheets/d/1i_8oM1KlmXo90zIIgNTdOg-M6xesTggFLnTkgmscMlI/edit#gid=0) 

## **CHARTERS MERGED:**

| SIG | Reviewed by| Notes |
|---|---|---|
| [SIG Auth](https://github.com/kubernetes/community/pull/2431) | @jbeda @philips @michelleN  | subprojects being enumerated (ref: https://github.com/kubernetes/community/pull/2525) |
| [SIG Service Catalog](https://github.com/kubernetes/community/pull/2233) | @philips @michelleN | followup to use new charter template|
| [SIG Cloud Provider](https://github.com/kubernetes/community/pull/2201) | | reviewed via [thread](https://groups.google.com/forum/#!topic/kubernetes-sig-cloud-provider/vvpvCDHKvw4), needs followup to use new charter template |
| [SIG CLI](https://github.com/kubernetes/community/pull/2453) | @pwittrock @bgrant0607 @spiffxp |  |
| [SIG Instrumentation](https://github.com/kubernetes/community/pull/2266) | @derekwaynecarr @spiffxp  | |
| [SIG Scalability](https://github.com/kubernetes/community/pull/2149) | @spiffxp @timothysc | tech leads need to be enumerated in sigs.yaml |
| [SIG Cluster Lifecycle](https://github.com/kubernetes/community/tree/master/sig-cluster-lifecycle) | @jbeda @bgrant0607  |  |
| [SIG Node](https://github.com/kubernetes/community/pull/2065) | @philips @bgrant0607 | |
| [SIG Storage](https://github.com/kubernetes/community/pull/2461) | @philips @quinton-hoole | |
| [SIG VMWare](https://github.com/kubernetes/community/pull/2300) | @philips @smarterclayton @spiffxp | |
| [SIG Scheduling](https://github.com/kubernetes/community/pull/2462/files) | @quinton-hoole @derekwaynecarr |  | 
| [SIG IBMCloud](https://github.com/kubernetes/community/pull/2555) | @spiffxp @derekwaynecarr | |
| [SIG Testing](https://github.com/kubernetes/community/pull/2777) | @brendandburns @dims |  |
| [SIG Multicluster](https://github.com/kubernetes/community/pull/2561) | @timothysc @spiffxp |  |
| [SIG Apps](https://github.com/kubernetes/community/pull/2881) | @bgrant0607 @smarterclayton |  |
| [SIG Architecture](https://github.com/kubernetes/community/pull/2804) | @jbeda @bgrant0607 (also @smarterclayton @brendandburns ) |  |
| [SIG AWS](https://github.com/kubernetes/community/pull/2733) | @philips @jbeda @spiffxp | under review |
| [SIG Windows](https://github.com/kubernetes/community/tree/master/sig-windows) | @philips @spiffxp | needs subprojects / areas of code listed| 
| [SIG Release](https://github.com/kubernetes/community/pull/2919) | @timothysc @spiffxp | |
| [SIG UI](https://github.com/kubernetes/community/pull/2821) | @dims @spiffxp  | | 
| [SIG Nework](https://github.com/kubernetes/community/pull/2744) | @dims @philips  | | 
| [SIG API Machinery](https://github.com/kubernetes/community/pull/2927) | @smarterclayton @bgrant0607 | |
| [SIG Autoscaling](https://github.com/kubernetes/community/pull/2425) | @spiffxp @brendandburns @michelleN  |   |
| [SIG Contributor Experience](https://github.com/kubernetes/community/pull/2843) | @spiffxp @sarahnovotny |   |

## **CHARTERS UNDER SC REVIEW:**

| SIG | Reviewed by | Notes |
|---|---|---|
| [SIG Docs](https://github.com/kubernetes/community/pull/3001) | @bgrant0607 @jbeda  @spiffxp |  @pwittrock has picked up 2019-01-15 |

## **CHARTERS MERGED WITHOUT/LIMITED SC REVIEW:**

| SIG | SC liasons | Notes |
| --- | --- | --- |
| [SIG PM](https://github.com/kubernetes/community/tree/master/sig-pm) | @sarahnovotny @spiffxp | Many differences from the template needing reconciliation, also no SC review AFAICT, see [this PR](https://github.com/kubernetes/community/pull/2068) | 

## **CHARTERS WE ARE HOLDING ON:**

| SIG | Reviewed by | Notes |
|---|---|---|
| [SIG Azure](https://github.com/kubernetes/community/blob/master/sig-azure/charter.md) | @brendandburns @sarahnovotny | was drafted prior to template, intend to fold into SIG Cloud Provider |
| [SIG Big Data](https://github.com/kubernetes/community/pull/2988) | @bgrant0607 @michelleN @spiffxp @timothysc | should be a WG |
| [SIG GCP](https://github.com/kubernetes/community/tree/master/sig-gcp) | @bgrant0607 @sarahnovotny | intend to fold into SIG Cloud Provider |
| [SIG OpenStack](https://github.com/kubernetes/community/tree/master/sig-openstack) | @spiffxp @dims | intend to fold into SIG Cloud Provider | 

## **CHARTER ISSUES/RECOMMENDATIONS:**

- SIG membership standardized
- Diversity and inclusion statement

## **TEMPLATE CHANGES REQUESTED:**

- Clear direction on how unresponsive chairs are removed, especially when a low number exists - see [this comment](https://github.com/kubernetes/community/pull/2040#discussion-diff-189472207R36)
- Separation of SIG and Sub-project roles - see [this PR](https://github.com/kubernetes/community/pull/2183)
- Something about how leadership lifecycle is managed - see [this issue](https://github.com/kubernetes/community/issues/1693)

## **SIGS TO BE SUNSET:**
| SIG | Assigned to | Notes |
|---|---|---|
| [SIG Cluster Ops](https://github.com/kubernetes/community/tree/master/sig-cluster-ops) | @sarahnovotny @michelleN | To be decommissioned per https://github.com/kubernetes/community/issues/2031 |

**Comment by jdumars** [comment]
For context, this was discussed [here](https://youtu.be/UKJYy9Oiuv0?t=2m27s)

**Comment by jdumars** [comment]
email sent to steering@ with a link to the new template: https://github.com/kubernetes/community/blob/master/committee-steering/governance/sig-charter-template.md

Further reference: https://github.com/kubernetes/community/tree/master/committee-steering/governance

**Comment by jdumars** [comment]
Re: SIG-VMWare (from the mailing list) -

@quinton-hoole wrote: "I added a comment to the https://github.com/kubernetes/community/pull/2300  The relationship between sig-vmware, and the cloud-provider-vsphere subproject of sig-cloud provider is unclear to me.  It seems that the two efforts should be collapsed into the latter (at least for now), or the compelling reasons for not doing so should be explicitly documented and approved."

**Comment by spiffxp** [comment]
I just rolled through the description and edited to the best of my ability, but uh, yeah, that was painful, and I'm pretty sure everything after "issues/recommendations" may be out of date because I didn't touch it.  Will be discussing during community meeting update today

**Comment by spiffxp** [comment]
Rolled through and updated again.

**Comment by spiffxp** [comment]
I reconciled a number of merged charters and reviewer assignments with the spreadsheet we used to initially assign SC reviewers.

**Comment by spiffxp** [comment]
Updated the issue and spreadhseet based on what I surveyed within kubernetes/community

**Comment by spiffxp** [comment]
We talked during steering today about potentially just not doing the work of writing a charter if a sig plans to fold into sig cloud provider.  Also a question of whether sig big data should actually be a wg instead.

**Comment by jdumars** [comment]
https://github.com/kubernetes/community/pull/2804 is probably ready for SC review given the lack of feedback

**Comment by justaugustus** [comment]
- SIG Release charter has merged after review from Aaron and Tim St. Clair - https://github.com/kubernetes/community/pull/2919
- SIG PM charter - next on the list to revise for me; hopefully before KubeCon, worst case, by EOY
- SIG Azure charter - I'm not going to bother refactoring this one, as the time would be better spent getting the SIG rolled under SIG Cloud Provider

**Comment by timothysc** [comment]
This issue is so old and stale, I'd like to propose that we close it and open a new issue with the current work items remaining.

**Comment by timothysc** [comment]
I will go through existing charters and see what needs to be changed.
