### ISSUE TITLE
EOL kubernetes-incubator

### ISSUE THREAD

**Issue by jdumars** [kubernetes/steering#34]
- Clarify the process for approving/vetoing incubator projects and mitigate sponsor shopping
- Update incubator process to explain new GitHub organization strategy
- Clarify graduation process

**Comment by spiffxp** [comment]
/assign
I'd like to instead repurpose this issue to document:
- if/when kubernetes-incubator repos are moving
- clarify the step by step process to migrate repos from kubernetes-incubator (or other orgs) to kubernetes-sigs
- ditto for making new repo

ref: https://github.com/kubernetes/community/issues/1922

**Comment by spiffxp** [comment]
/remove-lifecycle stale
/committee steering
Now that everything in kubernetes-incubator uses the same automation as kubernetes-sigs, moving repos from one place to the other is pretty much a matter of:
- finding sigs willing to own/sponsor these subprojects
- migrating members from kubernetes-incubator to kubernetes-sigs

**Comment by philips** [comment]
I think the only way we are going to get this done is by setting an EOL deadline and asking the repo maintainers to find a new home or create a new org that will make them an ["associated repo"](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#associated-repositories).

Does July 1st seem like enough lead time?

**Comment by nikhita** [comment]
Going to remove help-wanted since the GitHub Admin team is working on this: https://github.com/kubernetes/community/issues/1922.

/remove-help

**Comment by parispittman** [comment]
4 repos left; next few months

**Comment by cblecker** [comment]
Still four repos, but we have active communication with all sigs and have movement.

**Comment by mrbobbytables** [comment]
I think this may be safe to close at this point.
All AI's in the community tracking issue have been closed: https://github.com/kubernetes/community/issues/1922

The only outstanding issue that I know of is  a follow-up item in k/website to update their references: https://github.com/kubernetes/website/issues/24380

**Comment by nikhita** [comment]
Let's close this!

We can track the k/website issue separately IMO. :)
