### ISSUE TITLE
SIG charter template finalization

### ISSUE THREAD

**Issue by jdumars** [kubernetes/steering#35]
- Provide suggested governance
- List minimum required content
- Find commonalities across the current charter pool and update templates accordingly

**Comment by jdumars** [comment]
WIP: https://github.com/kubernetes/community/blob/master/committee-steering/governance/sig-charter-template.md

**Comment by michelleN** [comment]
Can this issue be closed since the SIG charter template was merged? and then can we open any other tickets if we need to iterate? or do we think there is more work to be done here? cc/ @pwittrock

**Comment by philips** [comment]
I think this is done.

/close
