### ISSUE TITLE
Resolve disconnects between code orgs and people orgs

### ISSUE THREAD

**Issue by jdumars** [kubernetes/steering#37]
Need to resolve the disconnect between code organization (OWNERS, maintainers) and people organization (SIGs), as well as figure out how to enforce this programatically

**Comment by justaugustus** [comment]
[Peribolos](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/peribolos) seeks to do this. 
From what I hear, we're close to being able to enable it on the org level.

cc: @fejta @cblecker

**Comment by philips** [comment]
@jdumars Is Peribolos a solution that would cover this issue?

**Comment by nikhita** [comment]
> Need to resolve the disconnect between code organization (OWNERS, maintainers) and people organization (SIGs)

@jdumars Can you elaborate on what you meant by disconnect here?

**Comment by timothysc** [comment]
@jdumars I really see this as a logistical issue for contribex, and not necessarily something that should be owned by steering.  I'm going to close this issue for @kubernetes/sig-contributor-experience-feature-requests to handle, but feel free to re-open if there are things that you think steering should be involved in.  For example, we may want final approval on a KEP that outlines how we want to handle this...

**Comment by nikhita** [comment]
> @kubernetes/sig-contributor-experience-feature-requests to handle, but feel free to re-open if there are things that you think steering should be involved in. 

Happy to take this on the contribex side. I'm still confused about what the issue means though. :)

@jdumars could you open an issue about this in k/community?

**Comment by fejta** [comment]
I believe we now enforce that people in OWNERS files are now members of the org.

**Comment by nikhita** [comment]
> I believe we now enforce that people in OWNERS files are now members of the org.

We don't do that yet :see_no_evil: 

There is nothing that checks that a user is an org member when they are being added to an OWNERS file (https://github.com/kubernetes/test-infra/issues/10553 is an open issue for that...fell out of my radar, will pick it up again).

We also need to do an audit of current OWNERS files. We have some with non org-members in them. Ref: https://github.com/kubernetes/kubernetes/issues/50048.
