### ISSUE TITLE
Code of Conduct documentation

### ISSUE THREAD

**Issue by jdumars** [kubernetes/steering#38]
- Update the Code of Conduct Committee to a more recent version 
- document enforcement
- broaden coverage beyond maintainers and committers
- handle coding activities and project/public spaces 
- specify our own reporting path
- clarify the policy on employer notification and who else may be involved
- decide what should be shared with the accused

**Comment by jdumars** [comment]
see: https://github.com/kubernetes/community/issues/1527

Most but not all repos are using a code of conduct that points to k/community, could use help chasing down remaining stragglers

**Comment by spiffxp** [comment]
/unassign
/committee conduct
I will leave this to the code of conduct committee

**Comment by bgrant0607** [comment]
This should be delegated to the CoC committee. Do they need a repo, or is the community repo sufficient?

**Comment by philips** [comment]
/assign @carolynvs @jdumars @parispittman @eparis @Bradamant3 

Based on https://github.com/kubernetes/community/tree/master/committee-code-of-conduct

**Comment by timothysc** [comment]
Folks is there any update on this?

**Comment by jdumars** [comment]
Still in progress. It turns out that this is delicate work staffed by very busy people.

**Comment by timothysc** [comment]
@michelleN - saw a note that she needed to review the charter. 
@parispittman - Currently blocked on the charter.

**Comment by timothysc** [comment]
Still working through charter agreements, and hopefully have steering review.

**Comment by timothysc** [comment]
There is a PR that should come through in a day or two

**Comment by spiffxp** [comment]
Charter PR https://github.com/kubernetes/community/pull/3663

**Comment by michelleN** [comment]
@kubernetes/steering-committee to vote
Need to add section on election/appointment process.

**Comment by spiffxp** [comment]
Agreed we don't need elections necessarily spelled out in charter, but need to spell out what election process for cocc is.  Michelle laid out a good start in https://github.com/kubernetes/community/issues/3353

**Comment by timothysc** [comment]
Given that they are formed closing this issue and we can address specific concerns on other issues.
