### ISSUE TITLE
Community resource management

### ISSUE THREAD

**Issue by jdumars** [kubernetes/steering#40]
- Document resources that the community has and make sure they have a home: releases, twitter handles, etc.

also, slack.

**Comment by timothysc** [comment]
All of the documentation is stored in the community repo.  
https://github.com/kubernetes/community/tree/master/communication 

https://docs.google.com/spreadsheets/d/1Pmlj5nN_QJ3rRlc-HKOLfRdYY5qCWPMjnNPAdZZ22tg/edit?usp=sharing 

Q: Question from @spiffxp - who actually owns the content? 
    - SIG docs doesn't actually own the content... 
Q: Linux Foundation / CNCF? 
A: Zach (Doc Writer) and Katelin are responsible for reviewing and approving the blog posts.  

AI: Follow up with sig-docs and ask if there are folks in the community who can own this?

**Comment by timothysc** [comment]
As a point of rectification - https://github.com/kubernetes/website/pull/12905

**Comment by timothysc** [comment]
process doc - https://docs.google.com/document/d/1uYM7lSNPpY5THAK8vx5RndCoYLQOrYgPtWlzrlvgirA/edit

**Comment by spiffxp** [comment]
Opened https://github.com/kubernetes/community/issues/3524 to cover formalizing blog duties as a subproject (of sig-docs? since the folks involved are in that SIG anyway)

**Comment by timothysc** [comment]
@spiffxp @parispittman - are there any other things we need todo here?
