### ISSUE TITLE
Find homes for unowned areas of the project

### ISSUE THREAD

**Issue by jdumars** [kubernetes/steering#41]
- build system (make, bazel, godep, etc.)
- util libraries
- Github org/repo management (e.g., dealing with Github changes, consistency across repos, etc.)
- Node controller
- kube-controller-manager binary
- hyperkube

**Comment by justaugustus** [comment]
Sounds like a fair amount of these things could be owned by the to-be-formed Release Engineering subproject, under SIG Release.

**Comment by philips** [comment]
@jdumars how do you think we should work through this list? I don't know where some of these things currently live or who initially created them. 

My only hunch is we identify the people who created the thing and ask them what SIG it should belong to and then just start assigning SIGs to own them.

**Comment by timothysc** [comment]
I believe @parispittman mentioned there was a spreadsheet on this one that we can follow up on during next meeting.

**Comment by timothysc** [comment]
re: Blog - Katlyn will help define policy and sig-docs will own as a sub-project.

**Comment by timothysc** [comment]
TODO: Follow up on this issue if we should close it out and open new ones.

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/community/issues/3524#issuecomment-480445006 for the blog

**Comment by tpepper** [comment]
> * build system (make, bazel, godep, etc.)

does feel like a natural thing to try to pull under SIG Release's nascent Release Engineering subproject.

**Comment by spiffxp** [comment]
@tpepper that was absolutely my intent in pushing for that (although godep is fuzzy and seems more like code org IMO)

**Comment by tpepper** [comment]
Choice of common tool and processes around healthy deps management fall in a broad build/test/release/support flow so will have multiple stakeholder SIGs and WGs imho.

**Comment by timothysc** [comment]
https://docs.google.com/spreadsheets/d/1Pmlj5nN_QJ3rRlc-HKOLfRdYY5qCWPMjnNPAdZZ22tg/edit#gid=0
