### ISSUE TITLE
Ecosystem project governance

### ISSUE THREAD

**Issue by jdumars** [kubernetes/steering#42]
- Decide how/whether ecosystem subprojects (e.g., kops, helm) are governed differently
- Develop policies/procedures for donated code (e.g., helm, kubernetes-anywhere, kompose, kargo)

**Comment by philips** [comment]
@jdumars Does this document help? What is missing? https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md

**Comment by timothysc** [comment]
I kind of think this is a non-issue anymore with the formation of hierarchy and subprojects.  Most major projects have found a landing zone, but I'll enqueue for us to discuss.

**Comment by philips** [comment]
Does the [associated repos document address](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#associated-repositories) the first point "Decide how/whether ecosystem subprojects (e.g., kops, helm) are governed differently"

On the second point who has handled donated code in the past? @michelleN on helm? @janetkuo on kompose? I am happy to make a more formalize document but the history is needed to start.

**Comment by janetkuo** [comment]
I believe @sebgoa handled the donation of kompose.

**Comment by sebgoa** [comment]
kompose was dontated as part of a software grant when I signed the Skippbox
CLA.

This was very hand wavy with no issues being raised. I did mention that
according to me that meant kompose was owned by CNCF, and that also meant
that any incubator project donated the same way were also CNCF projects.

-seb

**Comment by nikhita** [comment]
> Develop policies/procedures for donated code

We have rules for donated repos now: https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories

The [github-management team](https://github.com/kubernetes/community/tree/master/github-management#github-administration-team) is responsible for making sure that the rules are followed and also for taking care of the actual migration.

We have lots of donated repos in k-sigs today. Some issues about donated repos that are in progress right now: https://github.com/kubernetes/org/issues/467 and https://github.com/kubernetes/org/issues/599.

> I did mention that according to me that meant kompose was owned by CNCF, and that also meant that any incubator project donated the same way were also CNCF projects.

Also, when a repo is donated, it becomes a "normal kubernetes repo" and is essentially "owned" by CNCF. More details about the copyrights are being added in this PR: https://github.com/kubernetes/community/pull/3511.

---

Does this cover policies/procedures for donated code? What else do we want to have?

**Comment by philips** [comment]
I have gotten in touch with a few people on this but won't have time to start until next week.

**Comment by michelleN** [comment]
@philips +1 same here. Will get back on this next week.

**Comment by philips** [comment]
What @nikhita has provided seems sufficient to me. WDYT Michelle?

**Comment by philips** [comment]
What @nikhita has provided seems sufficient to me. WDYT Michelle?

**Comment by spiffxp** [comment]
I feel like this is sufficiently addressed by the docs above.  Donating a repo to the project means:
- that repo meets requirements such as using our automation and licensing
- that repo will be owned by a SIG either as a new subproject or part of an existing subproject, thus putting it under our usual governance
- our governance has an escalation path from subproject to sig to steering to handle exceptions on a case-by-case basis

I'll punt to the next milestone, but am looking for consensus to close

**Comment by michelleN** [comment]
@spiffxp will call for a vote on the mailing list to close this issue

**Comment by spiffxp** [comment]
https://groups.google.com/a/kubernetes.io/forum/#!topic/steering/8Sh8b1-cKFI

**Comment by spiffxp** [comment]
/close
I have not gotten a super-majority but am going to go ahead and close given no -1's.

If anyone believes this was closed in error please /reopen and let me know.

**Comment by philips** [comment]
sounds good, thanks.
