### ISSUE TITLE
Delegation of power to SIGs

### ISSUE THREAD

**Issue by jdumars** [kubernetes/steering#44]
- Need to explicitly delegate powers to SIGs
- Document this and socialize with the community

**Comment by spiffxp** [comment]
/committee steering
/remove-lifecycle stale
Once we have all charters merged I think we should see if this has been accomplished, or if there are still uncovered areas of responsibility, or areas where the steering committee is a bottleneck.

**Comment by philips** [comment]
I agree that charters merged will fix this.

**Comment by timothysc** [comment]
I think this requires a re-evaluation of what we have documented now and clarify where things are missing.

**Comment by philips** [comment]
@timothysc can you expand that thought? Between the description on this issue and your comment I don't know how we start on this.

**Comment by bgrant0607** [comment]
The charter was updated to include explicit delegation:
https://github.com/kubernetes/steering/blob/master/charter.md
