### ISSUE TITLE
Funding and budgeting

### ISSUE THREAD

**Issue by jdumars** [kubernetes/steering#46]
- Fund-requesting and budget processes needs to be formalized and documented

**Comment by timothysc** [comment]
Given recent conversations wrt to CNCF engagement, I'm going to triage for sooner rather than l8r.  
/cc @jbeda @philips

**Comment by philips** [comment]
@bgrant0607 made a comment on a steering call about some $xx threshold where we encourage maintainers to [directly make a service desk](https://github.com/cncf/servicedesk) request otherwise they need to escalate to steering.

I agree with this high level proposal

**Comment by dims** [comment]
+1 to $xx, though we still have to pick `xx` :)

**Comment by bgrant0607** [comment]
Doc about what CNCF projects need: https://docs.google.com/document/d/1HLRFOCgSleHX5ZHu3PQRTAVQB-KNjxggZxc6CFLLQxQ/edit

**Comment by timothysc** [comment]
What's going, what's the process, etc.

**Comment by philips** [comment]
I won't have time to start on this until next week.

**Comment by michelleN** [comment]
@philips same here

**Comment by philips** [comment]
I put an initial draft together here: https://docs.google.com/document/d/1EdBcK0SvzaJyWcY9g73haaN3cQD9xxwuJPaNuNcC2w8/edit#heading=h.bfoo7hg777e1

**Comment by timothysc** [comment]
@bgrant0607 @dims have singed up to review on 4/24

**Comment by dims** [comment]
@philips left a few questions/notes in the doc. thanks!

**Comment by philips** [comment]
@kubernetes/steering-committee I plan to just start implementing this after our next meeting May 15th if there are no objections.

**Comment by philips** [comment]
thanks @dims I had some followup on two of your comments.

I will put up a PR for this and then wait until May 28th or something for this to lazy consensus after KubeCon.

**Comment by dims** [comment]
Sounds good @philips

**Comment by philips** [comment]
PR is up https://github.com/kubernetes/steering/pull/106

**Comment by michelleN** [comment]
@kubernetes/steering-committee to vote

**Comment by philips** [comment]
I think this is done: https://github.com/kubernetes/funding/issues/new/choose

Closing.
