### ISSUE TITLE
Committee decision-making process

### ISSUE THREAD

**Issue by jdumars** [kubernetes/steering#47]
- Committee decision-making process (e.g., modified lazy consensus seeking) and quorum requirement

**Comment by LappleApple** [comment]
You might find some of these resources useful: https://github.com/LappleApple/awesome-leading-and-managing/blob/master/Influence-Delegation-and-Decision-Making.md

**Comment by timothysc** [comment]
Closing, as most of this is already documented and if there is an exact ask we can reopen.
