### ISSUE TITLE
Discussion topics meta-issue

### ISSUE THREAD

**Issue by jdumars** [kubernetes/steering#51]
- Do we need user groups?
- Do we need insurance?
- Do we need a policy similar to [Apache's release policy](http://www.apache.org/legal/release-policy.html)?
- Do we need a Conflict of Interest policy?

**Comment by nikhita** [comment]
This isn't particularly actionable. IMO we should close this and reopen new issues with specific concerns, if needed.

@kubernetes/steering-committee -- thoughts?

**Comment by nikhita** [comment]
Discussed this in the May 5th public steering committee meeting. We are good with closing this, but are happy to revisit any of them if the need arises.
