### ISSUE TITLE
Staffing gaps and conflict resolution

### ISSUE THREAD

**Issue by jdumars** [kubernetes/steering#52]
- Develop processes to address staffing gaps (engineering, docs, test, release, ...)
- effort gaps (tragedy of the commons)
- expertise mismatches
- priority conflicts
- personnel conflicts

**Comment by timothysc** [comment]
@parispittman could you or someone from @kubernetes/sig-contributor-experience-misc-use-only-as-a-last-resort give an update here?

**Comment by timothysc** [comment]
TL;DR - Closing this in favor of finer grained issues.  

However we should one specific issue on staffing gaps that exist across the project.  What were looking for is a more structured means by which we can address this issue.   @bgrant0607 will open the new issue.

**Comment by timothysc** [comment]
@michelleN suggested that we might want to survey the sig leadership on key staffing gaps.
