### ISSUE TITLE
Documentation requirements

### ISSUE THREAD

**Issue by jdumars** [kubernetes/steering#53]
- Determine how documentation policies are enforced with recommendations needed by SIG-Docs
- Integrate enforcement into the release process

**Comment by jdumars** [comment]
Discussed [here](https://youtu.be/UKJYy9Oiuv0?t=5m55s)

**Notes from the discussion:**

- SIG Docs really owns this issue
- Should alpha be documented in the repo?
- Who should docs ping for out of scope docs?
- Code is owned by people not SIGs so this presents a perpetual challenge
- Ownership and someone to poke every cycle

**PROPOSALS FOR DOC REVIEW TIMING:**
- @ KEP TIME (probably too soon)
- At check-in
- When Features get promoted
- On Release (too late)

**How to get docs done:**
- Guidance / Motivation need to be understood and exercised
- Automation
- Perhaps different types of LGTMs?
  - Review vs. technical
  - LGTMs by type?

- Docker has a lifecycle that depends on docs first

**Next steps:**
- Share the recording with SIG Docs, and let them come up with a proposal that the committee can review

**Comment by spiffxp** [comment]
/assign @jdumars 
for help on this

**Comment by jdumars** [comment]
https://youtu.be/I6BwkOA9dn4?t=2m39s

**Comment by parispittman** [comment]
per steering meeting today, we believe sig-docs has the necessary enforcement 

happy to take this up in steering at a later time

/close
