### ISSUE TITLE
Refresh the README

### ISSUE THREAD

**Issue by caniszczyk** [kubernetes/steering#6]
Now that the election is over for the KSC, the README should be refreshed with the members etc

**Comment by idvoretskyi** [comment]
cc @parispittman @castrojo @kubernetes/steering-committee

**Comment by castrojo** [comment]
If someone from the SC wants me to take a stab at this feel free to assign it to me.

**Comment by bgrant0607** [comment]
@castrojo Go for it. Thanks.
