### ISSUE TITLE
New repo request: Contributor site

### ISSUE THREAD

**Issue by jdumars** [kubernetes/steering#61]
From the mailing list: 

"SIG Contributor Experience would like to apply for a repo as part of our "community" subproject. We are working on generating a contributor.k8s.io site that will basically take all the markdown in k/community and generate a nicer site for us to use instead of passing around raw github links. 

Perhaps github.com/kubernetes-sigs/contributor-site with these owners: https://raw.githubusercontent.com/kubernetes/community/master/OWNERS

For reference here is the KEP for the contributor site: https://github.com/kubernetes/community/blob/master/keps/sig-contributor-experience/0005-contributor-site.md"

+1 from Sarah, Brian and Brandon as of 7/16/2018 ~ waiting for lazy consensus approval on 7/23/2018

**Comment by thockin** [comment]
+1

**Comment by jbeda** [comment]
Is the thinking that things would move from "community" to "contributor" and, in doing so be placed in a way that it is friendly for static sign generation?

Or is the thinking that there would be an automated system to copy/render things into that repo?

In other words -- would sigs.yaml move?

**Comment by spiffxp** [comment]
>In other words -- would sigs.yaml move?

My read of the KEP is no.

**Comment by spiffxp** [comment]
/assign
I'm happy to help create the repo once the sig has gotten lazy consensus

**Comment by jdumars** [comment]
https://youtu.be/I6BwkOA9dn4?t=1m48s

**Comment by jbeda** [comment]
Approved at the steering committee meeting. But I'm not sure about the process/permissions for creating it.  @spiffxp Can you do it?  (or point me at some docs if we have them so I can?)

**Comment by spiffxp** [comment]
/close
This has been done https://groups.google.com/a/kubernetes.io/forum/#!topic/steering/fnM_YG5ImKE
