### ISSUE TITLE
Steering committee elections 2018

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/steering#63]
Draft timeline:
- Election results announced - early Oct 2018? (‘t’)
- Open for votes - t-2 weeks?
- Announce who may vote (and allow exception applications) - t-4 weeks?
- Candidate bio distribution deadline - t-4 weeks?
- Candidate solicitation - t-6 weeks?
- Sounds like we need to kickstart the process ~early Aug (t-8 weeks).

**Comment by quinton-hoole** [comment]
Thanks.  I believe that @timothysc has such a dashboard already, and a proposed cutoff line score.  @parispittman just to clarify, are you willing to be an election officer?  In that case we have two volunteers, and ideally need to solicit a third.  Could you and George find a third, ideally from a third company?

There is a steering committee meeting today, where I'll make sure that the committee is OK with the above proposal, and the election officers should go ahead as described above.  Given that I'll be standing in the election, I'll bow out from involvement after that.

**Comment by timothysc** [comment]
> 3 - Select criteria for Kubernetes Members of Standing 

@jorge - The general roll'd up activity across the org, cut @ 50-60 for the last year was the general "ok" line that the steering committee thought was a reasonable metric   

https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=Last%20year&var-metric=contributions&var-repogroup_name=All

/cc @jbeda @spiffxp

**Comment by spiffxp** [comment]
Do you have a source for the 50-60? [I see 100 over one year in our meeting notes for 2018-05-09](https://docs.google.com/document/d/1qazwMIHGeF3iUh5xMJIJ6PDr-S3bNkT8tNLRkSiOkOU/edit#heading=h.w15bx222nkai)

**Comment by castrojo** [comment]
Just a reminder that we're blocking on the membership criteria. 

If that's still in progress we can at least move forward with election officers and schedule. @jberkus has shown interest in volunteering and can probably help us wrangle the info we need out of devstats. That would give us our third shadow from three different companies.

**Comment by quinton-hoole** [comment]
@spiffxp I was the one who said something like "about 100, from memory", which is what ended up in the notes.  I think @timothysc 's "50-60" is more accurate, and consistent with the demo given in the meeting.  Lets go with 50 over the trailing 12 months, to err on the side of inclusion.

**Comment by timothysc** [comment]
@spiffxp cut line is relatively arbitrary.

**Comment by timothysc** [comment]
@castrojo @parispittman - can you please start the ball rolling on elections and pick dates.  We need to get a move on this. 

/cc @kubernetes/steering-committee

**Comment by parispittman** [comment]
Updates
Draft schedule -

August 
15th - election announcement: who is eligible to vote, exception process for those who believe they should have a vote, and a request for nominations 


September 
14th - all canadidate bios / statement of intent is due
19th - voting begins; voters sent poll via email for selection 

October 
3rd - voting ends; poll closed and votes are tallied. Election officials 
4th - results are announced in weekly community meeting by TBD

Between now and Wednesday of next week:
- Finalize 3rd election official 
-Prepare the voting membership list that has a cut off of 50 or more contributions (already extracted from devstats but need to collect emails from another data source)
- Update election docs with new and updated details 
- Put together a small marketing campaign strategy and execute

**Comment by jberkus** [comment]
Wait, what's the process for non-GH contribution claims?  Do we already have a spec on that?

**Comment by parispittman** [comment]
@jberkus We will have a form to fill out and send it out to k-dev on the 15th.

**Comment by spiffxp** [comment]
I'd like to clear up where the one true copy of election rules should live, ref: https://github.com/kubernetes/community/pull/2542#issuecomment-413278573

**Comment by philips** [comment]
From the steering committee discussion everyone agreed that their should be
one copy and that the OWNERS of that file should be the steering committee.
We defer to you Aaron on the repo location.

**Comment by spiffxp** [comment]
https://github.com/kubernetes/community/pull/2547
https://github.com/kubernetes/steering/pull/68

**Comment by michelleN** [comment]
election ends on Oct. 3 on so I put an item to discuss next steps on the steering agenda for Oct. 10th

**Comment by spiffxp** [comment]
Updated kubernetes/steering with election results: https://github.com/kubernetes/steering/pull/79

Sundry other PR's and bits of administrivia completed.

We are awaiting a blog post with the results, @brendandburns volunteered, as have election officers.

**Comment by michelleN** [comment]
Going out Friday.
