### ISSUE TITLE
DCO vs. CLA discussion

### ISSUE THREAD

**Issue by jdumars** [kubernetes/steering#74]
Per Sarah Novotny:

We need to discuss the legal benefits of remaining on the CLA instead of moving to DCO. To get the expert perspective, I'd like to have one of our lawyers outline why Google is strongly supportive of CLAs.

**Comment by spiffxp** [comment]
Blocked on scheduling lawyers to have discussion w/ steering present

**Comment by timothysc** [comment]
/assign @sarahnovotny @bgrant0607

There was a CNCF meeting or survey that outlined the details, could those details be added here?

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/community/issues/2649

**Comment by bgrant0607** [comment]
CNCF contributor feedback is that DCO tooling needs improvement:
https://docs.google.com/presentation/d/1NkaMG5FUf06m6397A-wb3IW0ibjisyRBg3rUuUI7Mu0/edit#slide=id.g431f8d4ebc_0_28
