### ISSUE TITLE
Consolidate election information under steering?

### ISSUE THREAD

**Issue by castrojo** [kubernetes/steering#76]
For 2019 we should keep consolidating the process of the elections. SC did most of this for 2018 but we were running into a deadline, so people have two documents that they have to refer to:  

https://github.com/kubernetes/community/tree/master/events/elections/2018
https://github.com/kubernetes/steering/blob/master/elections.md

We should review and determine:

a) Specifically what should go in the overall steering election document.
b) Specifically decide what year-specific information should go in the voter guide.
c) Be more explicit about which steps are owned by SC and which steps are owned by the election officers.

It might also make sense to just move all the election documentation under steering so it's all in one place. Do they even need to be separate documents? etc. I'm mostly filing this so we remember to do it 1H 2019 so we don't run into a deadline.

**Comment by parispittman** [comment]
Process should be separate from policy imo bc we need to be owners for quick turn around PRs

**Comment by spiffxp** [comment]
I tried real hard to separate policy (k/steering) from process (k/community), but ultimately I found there was still a lot duplicated between the two docs.  For example, voter eligibility ended up being spelled out in all the places.

**Comment by timothysc** [comment]
Closing in favor of #81
