### ISSUE TITLE
Switch to Condorcet IRV method for 2019 election

### ISSUE THREAD

**Issue by castrojo** [kubernetes/steering#77]
Linux Foundation/CNCF use Condorcet/IRV for their elections. We use Condorcet/Schulze. We mostly picked Schulze because it's used by a bunch of OSS projects already and seemed like a good choice. 

I don't think it would hurt for us to just line up with LF/CNCF on this so that we're consistent. Switching method is trivial in CIVS, this just involves PRing the documentation to mention IRV instead of Schulze. 

Some information from @cra on the subject: http://www.daneckam.com/?p=374
Schulze information: https://en.wikipedia.org/wiki/Schulze_method

**Comment by timothysc** [comment]
I'm going to fold this under #76 because steering will need to resolve plans for 2019.

**Comment by timothysc** [comment]
Consolidating this under #76
