### ISSUE TITLE
Other election matters that need to be worked out/codified

### ISSUE THREAD

**Issue by parispittman** [kubernetes/steering#78]
- [ ] when does the steering committee engage the election officials? can we say July 1 every year is the date that steering kicks off election conversations? 
- [ ] when/how/who does steering committee codify the eligible voter definition every year? ie - are you using devstats, whats the cut off number? will election officials have this information no later than August 1?
- [ ] who makes the announcements?  blog, k-dev ml, k-dev slack, and Thursday Community Meeting (comm mtg is covered in docs and says SC but no other granularity)
- [ ] who lets the winners know if they are not already on SC?
- [ ] when and who PRs the winners into the SC README of listed members?
- [ ] when exactly does the term start and stop?

**Comment by timothysc** [comment]
Consolidating this under #76
