### ISSUE TITLE
Doc Needed - on and off boarding steering members

### ISSUE THREAD

**Issue by parispittman** [kubernetes/steering#80]
Would be good to have a doc for newly elected steering members and those who are retiring/off boarding/[insert leave reason here]. 

what mailing lists do they need to join? other access needed? should they just show up at the next meeting? should they prepare anything (bio for press?, docs to read/policies to become familiar with?)?

**Comment by nikhita** [comment]
xref https://github.com/kubernetes/steering/issues/132 - unconscious bias training as part of onboarding
