### ISSUE TITLE
Elections Meta-issue

### ISSUE THREAD

**Issue by jdumars** [kubernetes/steering#81]
Reference Issues:
[ #78 ] Other election matters that need to be worked out/codified 
[ #77 ] Switch to Condorcet IRV method for 2019 election
[ #76 ] Consolidate election information under steering?
[ #75 ] Codify election officer rotation and affiliation
[#48 ] Update and document Members of standing.

More TBD

**Comment by jdumars** [comment]
cc: @parispittman @castrojo

**Comment by spiffxp** [comment]
opened https://github.com/kubernetes/steering/pull/82 for some of these

**Comment by philips** [comment]
Which ones are left to be fixed @jdumars and @spiffxp?

**Comment by timothysc** [comment]
Welp I did consolidation too soon now I guess.

**Comment by michelleN** [comment]
members of standing and exception process is outstanding but this issue is done.

**Comment by bgrant0607** [comment]
Reopened #48
