### ISSUE TITLE
Cleanup / Audit of working groups

### ISSUE THREAD

**Issue by michelleN** [kubernetes/steering#83]
Using [this spreadsheet](https://docs.google.com/spreadsheets/d/1IqNkd-G2EveZem1PbG8aWGCDxbBhgHPhqwfethh5BoU/edit?usp=sharing) to track the audit.

**Comment by castrojo** [comment]
I was checking these as part of a contribex audit, here are ones that are inactive and their progress: https://github.com/kubernetes/community/issues/3188
