### ISSUE TITLE
CNCF dev rep from the KSC

### ISSUE THREAD

**Issue by caniszczyk** [kubernetes/steering#84]
Kubernetes Steering Committee:

You will recall that the CNCF governing board (GB) created 2 developer seats in 2017, one to be filled by a Kubernetes Steering Committee (KSC) member and one to be elected from the other (non-sandbox) CNCF-hosted projects. Details are here: https://github.com/cncf/foundation/blob/master/gb-developer-reps.md

Starting from the December 2017 GB meeting, Michelle Noorali was picked to represent the KSC (with a 1-year term) and Brandon Philips (based on being a CNI maintainer, not due to his KSC position) was elected for the other seat (with a 2-year term). The CNCF GB reviewed this process at its meeting this month and is not proposing any changes.

So, we request that the KSC reappoint Michelle or replace her, this time for a 2-year term. 

Thanks, and please let me know if you have any questions.

**Comment by spiffxp** [comment]
/committee steering
https://groups.google.com/a/kubernetes.io/forum/#!topic/steering/lHVWSNyiENo

**Comment by dims** [comment]
+1 to @michelleN

**Comment by dims** [comment]
@michelleN will continue as developer rep on the GB on behalf of the KSC per discussion in steering meeting (and subsequent update to the mailing list - https://groups.google.com/a/kubernetes.io/d/msg/steering/lHVWSNyiENo/2Mr9PimbAAAJ)

/close
