### ISSUE TITLE
Contributor Summit session prep

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/steering#85]
/committee steering
https://groups.google.com/a/kubernetes.io/forum/#!topic/steering/XAgW-JBICOQ

Need owner(s) to put together summaries of what we have done and what we are planning to do.

**Comment by michelleN** [comment]
- Organized SIG charters to help clarify roles, responsibilities and governance
- Created Code of Conduct Committee
- Solidified core values

**Comment by michelleN** [comment]
I think we should/could create some slides around the big ticket items we've worked on and then talk about why those were important and the impact we they will make.

**Comment by philips** [comment]
@michelleN The latest update is here: https://github.com/kubernetes/steering/issues/71#issuecomment-445090310

The security audit working group is documented here: https://github.com/kubernetes/community/tree/master/wg-security-audit

**Comment by philips** [comment]
@michelleN Oh, sorry, that is for the security audit (which we also got funding for IIRC).

Anyways, the bug bounty program is nearing the end of vendor selection. @mayakacz is helping to lead that.

**Comment by bgrant0607** [comment]
Contributor summit is over
