### ISSUE TITLE
Questions around some charter scope specifics

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/steering#86]
This came up during yesterday's SIG Release meeting.  They were looking for some clarification around:

>- Decide how and when official releases of Kubernetes artifacts are made and what they include
>- Declare a release, so that the committee can ensure quality/feature/other requirements are met.

Thus far it appears as though the steering committee has not been actively involved in either of these.  

My canned response was that we have been comfortable with SIG Release owning this from an execution perspective, and putting steering on the critical path would dramatically bottleneck us.  If it came down to changing the release process, or changing the definition of what a release includes, I would view steering as the escalation point of last resort, but would hope that SIG Release and SIG Architecture could work this out themselves.

(There are a number of other points where we have effectively delegated to other groups, and are merely around as escalation point of last resort.  But we haven't exhaustively listed this out, presumably because it's implied we're the escalation point of last resort for everything?)

For the purposes of scoping this issue, I'm interested in just these two release points.  Do we still need these points on our charter, do they need to be refined, or can they be dropped?

/committee steering
/sig release
/sig architecture

**Comment by justaugustus** [comment]
Closed via https://github.com/kubernetes/steering/pull/90.
/close
