### ISSUE TITLE
Select representative for the CNCF GB

### ISSUE THREAD

**Issue by caniszczyk** [kubernetes/steering#9]
Now that the KSC is formed, they should select a represented amongst themselves to be on the CNCF GB: https://github.com/cncf/foundation/blob/master/gb-developer-reps.md

Could this be done by the end of next month so the representative could join us at the next CNCF GB meeting in December at KubeCon/CNCon?

**Comment by philips** [comment]
Its on the backlog. I will add it to our agenda for next time.

https://github.com/kubernetes/steering/blob/master/backlog.md#backlog-items

**Comment by caniszczyk** [comment]
@philips and the @kubernetes/steering-committee 

Has this been done yet? We'd like you to pick their GB representative by 12/3 for the 12/5 GB meeting. That person will need to miss the Contributor Summit from 1 to 4 PM.

When is the next KSC meeting?

**Comment by timothysc** [comment]
@michelleN Volunteered as tribute during our last meeting.  I'm a +1 for her representing the committee.

**Comment by bgrant0607** [comment]
@caniszczyk Yes, @michelleN is the K8s GB rep.

**Comment by dankohn** [comment]
Fantastic! (And @timothysc I love the Hunger Games reference.)
