### ISSUE TITLE
Document process for User Groups formation

### ISSUE THREAD

**Issue by nikhita** [kubernetes/steering#92]
Ref: https://github.com/kubernetes/community/pull/3299#issuecomment-467699660

User Groups were added as a community group in https://github.com/kubernetes/community/pull/3174. Given that we are also adding a `usergroups` field to `sigs.yaml` (https://github.com/kubernetes/community/pull/3298), it would be good to have processes defined and documented for formation of User Groups.

The doc should go here: https://github.com/kubernetes/community/tree/master/committee-steering/governance

/committee steering

**Comment by timothysc** [comment]
Is there anything else we need todo here?

**Comment by nikhita** [comment]
> Is there anything else we need todo here?

Yes, we need a governance doc for User Groups - just like we have for SIGs and WGs in https://github.com/kubernetes/community/tree/master/committee-steering/governance. 

Basically, a doc outlining the different roles in a User Group (leads, chairs?), creation and retirement process.

**Comment by nikhita** [comment]
Oh, I just noticed the `help wanted` label on this.

I'm happy to help move this forward given that we are in the process of adding a new user group (https://github.com/kubernetes/community/pull/3304) but I think the doc needs to come from steering and I'm not sure how anyone non-steering can help? :thinking:

**Comment by timothysc** [comment]
@pwittrock - thx for helping out here.

**Comment by timothysc** [comment]
@jbeda - could you outline your thoughts here?

**Comment by jbeda** [comment]
Haha -- not sure I can own this but I do see a certain level of overlap here between User Groups (from a governance point of view) and geographic based meetups.  There is a community with leaders and standards.  In return they get to use the Kubernetes name.

We should perhaps look to join the streams here and leverage any work that is being done around CNCF chartered meetups.

@parispittman @idvoretskyi Do you have thoughts/details?

**Comment by jberkus** [comment]
@jbeda the CNCF already manages meetups.  We don't need to add more things to manage.  And, speaking as a meetup organizer, I really don't need to change this.

**Comment by jberkus** [comment]
@jbeda:  CNCF uses Meetup.com for meetup groups.  They really don't provide any support, or do any work, aside from that, except for periodic pizza sponsorship.  Meetup.com is not an adaptable or customizable platform, so it wouldn't be suitable for UGs.

**Comment by idvoretskyi** [comment]
@jberkus we do provide much wider support for the Meetup groups except for the periodic pizza sponsorship (we may chat about that independently from this case if you have any concerns), but in general you are right - meetup.com is not a platform that was designed for UG use cases.

**Comment by timothysc** [comment]
AI: @pwittrock will send out an email soliciting folks from the community to help draft a document and timeout in a couple of weeks if no one steps up.

**Comment by pwittrock** [comment]
@daminisatya will lead and I will support.

**Comment by surajnarwade** [comment]
@timothysc , @dims 
I would like to help also :)

**Comment by oicheryl** [comment]
I'd also like to be in the loop as I run the CNCF End User Community (https://www.cncf.io/people/end-user-community/) and the groups under it.

**Comment by daminisatya** [comment]
Hello All! 

@pwittrock Helped me get started and I'm actively working on defining the structure for UGs governance ( done with defining creation and deletion of UGs) Will keep you posted on this thread! ✨

**Comment by pwittrock** [comment]
FYI, we have a draft out that will be published in the next day or 2

**Comment by daminisatya** [comment]
Some last-minute hiccup and will be opening a PR by Tuesday morning (PST) 😄

**Comment by d-nishi** [comment]
@daminisatya -- can you add me to this thread please?

**Comment by daminisatya** [comment]
@d-nishi You can check the PR, I referenced here!

**Comment by michelleN** [comment]
documentation PR merged. Thanks @daminisatya
