### ISSUE TITLE
Clarify and improve how we identify and close staffing gaps across the project

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/steering#94]
This supersedes the "staffing gaps" part of https://github.com/kubernetes/steering/issues/52

We don't have a systematic way to identify, advertise, and fill areas that need to be staffed across the project, except in a few areas, such as the release team.

There are at least 3 areas:
1. Work within SIGs and committees. This is why we created the role board. But most SIGs haven't defined roles. Developing some suggested roles may help.
2. Identifying which SIGs most need help. We've done this sporadically, with SIG UI, SIG Docs, and a few other areas, but don't have a systematic way of surfacing these needs.
3. Areas that fall outside the SIGs. We're trying to minimize such areas, but some still exist. The K8s Infra WG is a recent example of an effort to move something forward that doesn't cleanly fall under any particular SIG.

@michelleN suggested a meeting with SIG Chairs/Leads to help identify gaps.

**Comment by spiffxp** [comment]
This issue is about creating/documenting "a systematic way to identify, advertise, and fill areas that need to be staffed across the project"

My suggestion would be document how annual reports will be / are used to do this, document gaps, then close out.

Areas that need improvement = other issues

**Comment by parispittman** [comment]
I think this can be closed - woohoo! 🎊  As @spiffxp mentioned, we now have the [annual report process](https://github.com/kubernetes/community/blob/master/committee-steering/governance/annual-reports.md) to help ID different kinds of gaps, including staffing. 

Also in place:
- monthly SIG/WG Lead meeting where we can surface needs on a regular basis 
- steering liaisons for each SIG/WG https://github.com/kubernetes/community/pull/5415

**Comment by parispittman** [comment]
we also started documenting roles here https://github.com/kubernetes/community/blob/master/mentoring/programs/shadow-roles.md

and continuing the conversation here: https://github.com/kubernetes/community/pull/5736

**Comment by parispittman** [comment]
closing this now that the annual report process is live and the first report is published 
https://www.cncf.io/reports/kubernetes-community-annual-report-2020/
