### ISSUE TITLE
We've lost our definition of quroum

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/steering#97]
https://github.com/kubernetes/steering/search?q=quorum&unscoped_q=quorum

https://github.com/kubernetes/steering/blob/658f53a67d9f15db9b50388ec362c683f9bdee4d/CONTRIBUTING.md
>Large changes and PRs [ ...] Ensure there is live discussion by a quorum of members.

https://github.com/kubernetes/steering/blob/34cd4481557f1e11df190d1cb46965b41a087e95/README.md
>We meet privately online at Wed 1pm PT every other week if there is quorum

https://github.com/kubernetes/steering/pull/18 dropped the section on our meetings, which contained the definition

>Regular steering committee meetings will be held, at least once per month. The	
entire steering committee is generally expected to attend every meeting, but	
**quorum is met with 2/3 attendance**. If a member misses more than 50% of all	
meetings held within a six month period then they will be removed from the	
committee and a special election will be held. Recorded videos of the meetings	
will be made publicly available in a timely manner.	

>Non-recorded, closed meetings are reserved for confidential matters (for	
example code of conduct issues) which are not appropriate to be shared with the	
broader community. Steering committee **meetings can be made closed by a simple	
majority vote** of the steering committee members, but closed meetings do not	
count towards the required meeting frequency. The steering committee will	
inform the community if a particular meeting is closed, as well as the general	
reasons for this, prior to the meeting taking place.

https://github.com/kubernetes/steering/blob/master/changes.md says this about votes that pertain to how the committee operates

>At any time prior to acceptance, a steering committee member may call a vote. A vote is scheduled no later than 4 weeks after initial introduction of the change. A vote may be scheduled earlier if all committee members agree. The change is accepted if **three-fourths of the committee members vote in favor**.

https://github.com/kubernetes/steering/blob/master/charter.md says nothing about how we vote

I believe it is critical that we document how we do things, because I believe we're operating under tribal knowledge at the moment.  AFAIK
- we have quorum to meet with over 1/2 attendance (eg: [steering@ thread to cancel if we hit 6/12](https://groups.google.com/a/kubernetes.io/d/msg/steering/v6QsVaLcOMA/VQp4QQ1zAAAJ), [steering@ thread to cancel because we hit 5/12](https://groups.google.com/a/kubernetes.io/d/msg/steering/fmNYvZwrDTM/JObwFsFJDQAJ)
- we have quorum for a binding vote with 2/3 attendance

/assign

**Comment by dims** [comment]
+1 to 1/2 for attendance and 2/3 for binding vote in principle ... how do we do this with odd number of folks?

**Comment by spiffxp** [comment]
With 12 members:
- quorum to meet at 6/12
- quorum to vote at 9/12

I haven't yet found a thing showing how we operated with 13, but I would suggest we round up at an odd number.  I am totally fine punting to our four-weeks-with-3/4-vote decision for the rest of this comment if it holds up documenting what we do today with 12.

With 11 members:
- quorum to meet at 6/11
- quorum to vote at 9/11

With 7 members:
- quorum to meet at 4/7
- quorum to vote at 6/7

We also really lack anything suggesting how/when we go to a written binding vote for decisions that don't impact how the steering committee functions, and what the requirements are there.

https://github.com/kubernetes/community/blob/master/sig-wg-lifecycle.md#prerequisites-for-a-wg calls for a simple majority from steering for WG creation.  I would extend that to any of our written votes.

**Comment by spiffxp** [comment]
Opened PR https://github.com/kubernetes/steering/pull/101
