### ISSUE TITLE
leadership trainings

### ISSUE THREAD

**Issue by tpepper** [kubernetes/steering#98]
In other large projects with technical oversight or steering committees, I've observed that the associated foundation has funded various types of baseline and ongoing training when major boards are established or as membership turns over.  Education around topics such as unconscious bias, decision making, conflict resolution, code of conduct violation/response trainings exist in industry to insure boards have standard leadership tool knowledge to be the most effective they can be.  I would find it inspirational and confidence boosting to know our project leadership (perhaps including SIG/WG chairs too?) had access to these tools and that it was valued by CNCF to the point of funding these consultations and trainings.

**Comment by michelleN** [comment]
I agree 100% and would love to see this happen. would love to get thoughts from the rest of @kubernetes/steering-committee

**Comment by timothysc** [comment]
We're going to close this issue and punt to contribex

**Comment by dims** [comment]
I'd highly recommend  https://www.zingtrain.com/leadership-development  (i've attended one with OpenStack leaders and it was great!)

**Comment by michelleN** [comment]
At the last steering meeting, everyone seemed to be on board with going ahead and taking an unconscious/gender bias training. I've been asked if we have a vendor in mind? The LF also has an [inclusive speaker training](https://training.linuxfoundation.org/training/inclusive-speaker-orientation/) course that covers these kinds of thing. Should we(steering) take that? 

Does anyone have thoughts or recommendations on how we should move forward?

**Comment by philips** [comment]
the LF class looks like a reasonable start from the web page brief @michelleN

**Comment by michelleN** [comment]
Steering members, please take the course and report back here within the next month.

**Comment by dims** [comment]
DONE! it was really useful. i did an exercise on Project Implicit [1] as well that the training talks about. I'd encourage you to try one as well!

[1] https://implicit.harvard.edu/implicit/takeatest.html

**Comment by philips** [comment]
I finished the LF unconscious bias course just now as well.

Feedback: The course material was OK but I feel as if it could have used better evidence in places and near the end started to repeat itself a bit through the "evidence based approach" slides.

Overall, I think we might should evaluate other resources for future Kubernetes steering members or contributors.

**Comment by michelleN** [comment]
michelle to remind steering to do this cc/ @kubernetes/steering-committee

**Comment by timothysc** [comment]
We have a PR in now that documents the need, and I'll open an issue for us to check off that all members have done it.  Closing this and creating a new one.
