### ISSUE TITLE
Basic governance of sub-projects.

### ISSUE THREAD

**Issue by timothysc** [kubernetes/steering#99]
There have been a number of questions regarding governance of subprojects that we should look to formalize, which should include:

- What rules apply to sub-projects if the core depends on them?  e.g. CNI, CRI, CSI, AddOns 
- What processes and policies should be followed for the administration of those repos. (e.g. voting plus timeout?)
- Better clarification around any guarantees WRT sub-projects vs. core.  

Ideally we'd still try to hold true to the notion that we need a space for sigs to explore projects without the burden of core processes.  

@smarterclayton @bsalamat @brendandburns @dims @bgrant0607

**Comment by dims** [comment]
Please see https://groups.google.com/forum/#!msg/kubernetes-sig-scheduling/qvdcZ9kFqZE/q1f6zlQRCwAJ

**Comment by dims** [comment]
fyi, @k82cn has changed the repo name back for now until there is a community consensus.

**Comment by smarterclayton** [comment]
As a general, rule we've tried to

1. Split kube from a monolithic entity into an ecosystem of sigs
2. Retain tight rules on the core kube to keep it from growing unbounded
3. Encourage experimentation in sigs

I think that has been successful - the problems Tim lists are exactly the sort of "next step problems"

4. Things sigs create become "part of Kubernetes" but are not "part of core Kubernetes" - are we all comfortable with that line and the rules?
5. Does the quality / name association of all sig projects create a governance responsibility or a requirement to hold sigs to a standard?
6. How far can a sig experiment before it is something that is just "yet another ecosystem project that doesn't need to be part of a sig"?

I think the analogy I'm noticing is to OpenStack Stackforge - should kubernetes-sigs be that equivalent?  OpenStack had a well defined incubation process - https://governance.openstack.org/tc/reference/incubation-integration-requirements.html that ultimately incentivized companies to create sub projects and integrate them.  Is that what we want for Kubernetes?

**Comment by timothysc** [comment]
> Things sigs create become "part of Kubernetes" but are not "part of core Kubernetes" - are we all comfortable with that line and the rules?

I think we should call out this distinction, and we tried to in the beginning (e.g. kubernetes-incubator)  They are clearly not core and thus not kubernetes, but in it's orbit.  We discussed this point ad-nauseam during the creation of the model. 

> Does the quality / name association of all sig projects create a governance responsibility or a requirement to hold sigs to a standard?

I'm ok with projects of varying quality coming and going and having this be a sig-responsibility to curate, but I also think we should explicitly set the expectations of things under kubernetes-sigs.  The same comment applies from the previous point.

> How far can a sig experiment before it is something that is just "yet another ecosystem project that doesn't need to be part of a sig"?

I think that should be spelled out in the charter.  If it's in scope for the charter, then is makes sense for the SIG to still house otherwise probably not.

**Comment by k82cn** [comment]
> I think that should be spelled out in the charter. If it's in scope for the charter, then is makes sense for the SIG to still house otherwise probably not.

Is it possible to also include few items that out of scope for the charter? I'm not sure whether you remembered "kube-arbitrator", most of its items are about scheduling but `QueueJob` maybe sig-apps. IMO, it should be fine to have such kind of overlap if related sigs's ok.
